#+STARTUP: showeverything

* 耶鲁大学公开课－死亡

  #+BEGIN_CENTER
  死亡一直是中国一个很避讳的话题，从古代的王侯将相贩夫走足还是到现代的官商士绅市井民众，似乎都很难面对这样一个现实：死亡是一个自然规律，你能做的就是坦然的面对他。
  这个课程的教授他委委道来，用专业的知识向我们讲述死亡这个在中国鲜有人敢提及的现象，弥补了我们对这个自然宿命的知识的欠缺。
  #+END_CENTER

** 关于这个课程

   - 课程介绍[fn:1]
   我可以肯定的是，我将会死去。 但是我要怎么去看待这个事实呢？ 本课程将研究关于死亡的许多问题：
   1. 如果死亡并不是一种终结，那从某种意义上来说我们是不朽的吗？永生不好吗？
   2. 对死亡的过程将有一个更清晰认识，说一个人死了意味着什么？死亡是一个怎样的事实？
   3. 最后，评估了对死亡的不同态度。 死亡是邪恶的吗？ 怎么样算邪恶？ 为什么是邪恶的？ 自杀在道德上是允许的吗？ 合理吗？ 我认识到自己将会死亡的事实将如何影响我现在的生活？

   - 关于课程
   这个课程在耶鲁官网[fn:2]，youtube[fn:3], 和网易公开课上[fn:4]都可以观看。这个课程的意义在于让我们重新认识我们不敢面对的死亡。
   关于雪莉·卡根（Shelly Kagan）（/ ˈkeɪ）ən/）（生于1956年）是耶鲁大学的克拉克哲学教授，自1995年以来一直在该大学任教。
   他以关于道德哲学和规范伦理学的著作而闻名。2007年，卡根关于死亡的课程在网上免费提供，并且非常受欢迎。这导致他于2012年出版了有关该主题的书。他于2016年当选为美国艺术与科学学院院士。[fn:5]
   该课程为英文课程，网易上的资源有专业的团队做了翻译，但是我想通过自己的努力在观看原版视频的前提下作一个总结吧。该课程偏向人文哲学方面，所以你也可以畅所欲言阐述你自己的观点。

** 第一课－课程介绍



* Footnotes

[fn:5] https://en.wikipedia.org/wiki/Shelly_Kagan

[fn:4] http://open.163.com/special/sp/philosophy-death.html

[fn:3] https://www.youtube.com/watch?v=p2J7wSuFRl8&t=33s

[fn:2] https://oyc.yale.edu/death/phil-176

[fn:1] https://oyc.yale.edu/death/phil-176
