:PROPERTIES:
:ID:       75d9d82e-5c03-42dd-80c0-27e5d57318be
:END:
#+STARTUP: showall
#+options: toc:nil

* 读报任少卿书-司马迁作史记的心境

我们讲中国学问重功夫，西方学问重方法。方法很好理解，就是通过不同的手段来达到目地，而这个所谓的功夫体现在哪里？史记作为史家之绝唱，无韵之离骚为什么会被这么多圣贤人士奉为经典呢？司马迁是做了多少努力我们今天才能有机会看到这本经典的书呢？而这本书的成书又经历了多少的坎坷？司马迁想通过这本书告诉我们什么呢？做为正史鼻祖，散文大宗司马迁又是以什么样的心境完成这本书，让这本书充满了灵魂？读完这封书信会得到想要的答案。

#+toc: headlines

#+begin_quote
办大事者，以多选替手为第一义

--曾国潘
#+end_quote

史记一百三十篇，篇篇都在塑造人物，篇篇都在描写时代，篇篇都有独到之处。以其首创纪传、包含五体[fn:1]、贯通古今、体大思精成为正史鼻祖; 以其文章雄[fn:2]、逸[fn:3]成为散文大宗[fn:4]; 以其独创的史家思想成一家之言[fn:5]; 以其继春秋，拔乱世反诸正，为治理天下的百王大法。他是如何成书的呢？

** 这封信的开端：一场父子之间的悲剧

报任少卿书写于征和二年，这一年发生了巫蛊之祸。事情起因是汉武帝长子兼皇位繼承人——太子刘据因被弄臣術士江充、苏文等人誣陷以巫蛊詛咒父親，在无法自辩的情况下被迫發兵起事诛杀江充，导致汉武帝以为儿子企图谋反而派丞相刘屈牦带兵镇压。两方对战导致长安城中死伤过万，最後太子兵败逃亡，在被追剿无路可逃之后自縊而死。其後汉武帝醒悟為太子平反又進行一波肅清。

巫蛊之祸从发端到结尾，前后罹难有数萬人，大量政治军事人才流失成为西汉政权的衰落重要的历史原因。如此以屠戮骨肉姻亲为主要对象的狱案，其时间之长、影响之大在中国历史上实属罕见[fn:6]。

** 任少卿是谁

而任少卿又是谁呢？

** 独抑郁而无谁语

#+begin_quote
太史公牛馬走司馬遷再拜言少卿足下：

曩者辱賜書，教以慎於接物，推賢進士爲務。意氣懃懃懇懇，若望僕不相師，而用流俗人之言。

僕非敢如是也。僕雖罷駑，亦嘗側聞長者之遺風矣。顧自以爲身殘處穢，動而見尤，欲益反損，是以獨鬱悒而誰與語？
#+end_quote

** 则长逝者魂魄私恨无穷

#+begin_quote
諺曰：「誰爲爲之？孰令聽之？」蓋鍾子期死，伯牙終身不復鼓琴。何則？士爲知己者用，女爲説己者容。若僕大質已虧缺矣，雖才懷隨和，行若由夷，終不可以爲榮，適足以發笑而自點耳。
#+end_quote

#+begin_quote
書辭宜答，會東從上來，又迫賤事，相見日淺，卒卒無須臾之間，得竭志意。今少卿抱不測之罪，涉旬月，迫季冬；僕又薄從上雍，恐卒然不可為諱。是僕終已不得舒憤懣以曉左右，則長逝者魂魄私恨無窮。

請略陳固陋，闕然久不報，幸勿為過。
#+end_quote

** 尚何言哉！尚何言哉！

#+begin_quote
僕聞之：修身者，智之符也；愛施者，仁之端也；取予者，義之表也；恥辱者，勇之決也；立名者，行之極也。士有此五者，然後可以託於世，列於君子之林矣。
#+end_quote

#+begin_quote
故禍莫憯於欲利，悲莫痛於傷心，行莫醜於辱先，而詬莫大於宮刑。刑餘之人，無所比數，非一世也，所從來遠矣。昔衞靈公與雍渠同載，孔子適陳；商鞅因景監見，趙良寒心；同子參乘，袁絲變色。自古而恥之。
#+end_quote

#+begin_quote
夫以中材之人，事有關於宦豎，莫不傷氣，而況於慷慨之士乎！如今朝廷雖乏人，柰何令刀鋸之餘薦天下豪俊哉！
#+end_quote

#+begin_quote
僕賴先人緒業，得待罪輦轂下，二十餘年矣。所以自惟，上之，不能納忠效信，有奇策才力之譽，自結明主；次之，又不能拾遺補闕，招賢進能，顯巖穴之士；外之，不能備行伍，攻城野戰，有斬將搴旗之功；下之，不能積日累勞，取尊官厚祿，以爲宗族交遊光寵。

四者無一遂，苟合取容，無所短長之效，可見於此矣。
#+end_quote

#+begin_quote
嚮者，僕亦嘗廁下大夫之列，陪奉外廷末議。不以此時引綱維，盡思慮；今以虧形爲掃除之隸，在闒茸之中，乃欲仰首伸眉，論列是非，不亦輕朝廷，羞當世之士邪！

嗟乎！嗟乎！如僕尚何言哉！尚何言哉！
#+end_quote

** 李陵之战的真相

#+begin_quote
且事本末未易明也。僕少負不羈之才，長無鄉曲之譽，主上幸以先人之故，使得奉薄伎，出入周衞之中。僕以爲戴盆何以望天，故絶賓客之知，亡室家之業，日夜思竭其不肖之材力，務一心營職，以求親媚於主上。而事乃有大謬不然者。
#+end_quote

#+begin_quote
夫僕與李陵俱居門下，素非能相善也。趣舍異路，未嘗銜盃酒，接殷勤之餘懽。

然僕觀其爲人，自守奇士，事親孝，與士信，臨財廉，取與義，分別有讓，恭儉下人，常思奮不顧身，以殉國家之急。其素所畜積也，僕以爲有國士之風。
#+end_quote

#+begin_quote
夫人臣出萬死不顧一生之計，赴公家之難，斯已奇矣。今舉事一不當，而全軀保妻子之臣隨而媒孽其短，僕誠私心痛之。
#+end_quote

#+begin_quote
且李陵提步卒不滿五千，深踐戎馬之地，足歴王庭，垂餌虎口，橫挑彊胡，仰億萬之師，與單于連戰十有餘日，所殺過當。
#+end_quote

** 明主不深晓？

#+begin_quote
虜救死扶傷不給，旃裘之君長咸震怖，乃悉徵其左右賢王，舉引弓之人，一國共攻而圍之。轉鬭千里，矢盡道窮，救兵不至，士卒死傷如積。

然陵一呼勞軍，士無不起，躬自流涕，沬血飲泣，更張空弮，冒白刃，北嚮爭死敵者。
#+end_quote

#+begin_quote
陵未沒時，使有來報，漢公卿王侯皆奉觴上壽。後數日，陵敗書聞，主上爲之食不甘味，聽朝不怡。大臣憂懼，不知所出。
#+end_quote

#+begin_quote
僕竊不自料其卑賤，見主上慘愴怛悼，誠欲效其款款之愚，以爲李陵素與士大夫絶甘分少，能得人之死力，雖古之名將，不能過也。身雖陷敗，彼觀其意，且欲得其當而報漢。事已無可柰何，其所摧敗，功亦足以暴於天下矣。
#+end_quote

#+begin_quote
僕懷欲陳之，而未有路，適會召問，即以此指推言陵之功，欲以廣主上之意，塞睚眥之辭。

未能盡明，明主不曉，以爲僕沮貳師，而爲李陵遊説，遂下於理。拳拳之忠，終不能自列。因爲誣上，卒從吏議。
#+end_quote

** 此正少卿所亲见

#+begin_quote
家貧，貨賂不足以自贖，交遊莫救視；左右親近不爲一言。身非木石，獨與法吏爲伍，深幽囹圄之中，誰可告愬者！

此真少卿所親見，僕行事豈不然邪？李陵既生降，頹其家聲；而僕又佴以蠶室，重爲天下觀笑。悲夫！悲夫！事未易一二爲俗人言也。
#+end_quote

** 死有重于泰山，有轻于鸿毛

#+begin_quote
僕之先，非有剖符丹書之功，文史星暦，近乎卜祝之間，固主上所戲弄，倡優所畜，流俗之所輕也。

假令僕伏法受誅，若九牛亡一毛，與螻螘何以異？而俗又不能與能死節者次比，特以爲智窮罪極，不能自免，卒就死耳。何也？素所自樹立使然也。人固有一死，死或重於泰山，或輕於鴻毛，用之所趣異也。
#+end_quote

#+begin_quote
太上不辱先，其次不辱身，其次不辱理色，其次不辱辭令，其次詘體受辱，其次易服受辱，其次關木索、被箠楚受辱，其次剔毛髮、嬰金鐵受辱，其次毀肌膚、斷肢體受辱，最下腐刑，極矣。
#+end_quote

#+begin_quote
傳曰：「刑不上大夫。」此言士節不可不勉勵也。猛虎在深山，百獸震恐，及其在檻穽之中，搖尾而求食，積威約之漸也。故士有畫地爲牢，勢不可入，削木爲吏，議不可對，定計於鮮也。
#+end_quote

#+begin_quote
今交手足，受木索，暴肌膚，受榜箠，幽於圜牆之中。當此之時，見獄吏則頭搶地，視徒隸則心惕息。

何者？積威約之勢也。及已至是，言不辱者，所謂彊顏耳，曷足貴乎！
#+end_quote

#+begin_quote
且西伯，伯也，拘於羑里；李斯，相也，具於五刑；淮陰，王也，受械於陳；彭越、張敖，南面稱孤，繫獄抵罪；絳侯誅諸呂，權傾五伯，囚於請室；魏其，大將也，衣赭衣，關三木；季布爲朱家鉗奴；灌夫受辱於居室。
#+end_quote

** 恨私心有所不尽

#+begin_quote
此人皆身至王侯將相，聲聞鄰國，及罪至罔加，不能引決自裁，在塵埃之中，古今一體，安在其不辱也！
#+end_quote

#+begin_quote
由此言之，勇怯，勢也；彊弱，形也。審矣！何足怪乎？夫人不能蚤自裁繩墨之外，以稍陵遲至於鞭箠之間，乃欲引節，斯不亦遠乎！
#+end_quote

#+begin_quote
古人所以重施刑於大夫者，殆爲此也。夫人情莫不貪生惡死，念父母，顧妻子，至激於義理者不然，乃有所不得已也。今僕不幸，蚤失二親，無兄弟之親，獨身孤立，少卿視僕於妻子何如哉？
#+end_quote

#+begin_quote
且勇者不必死節，怯夫慕義，何處不勉焉！僕雖怯懦，欲苟活，亦頗識去就之分矣，何至自沉溺縲紲之辱哉！

且夫臧獲婢妾，猶能引決，況僕之不得已乎！所以隱忍苟活，幽于糞土之中而不辭者，恨私心有所不盡，鄙陋沒世，而文[fn:7]采不表於後世也。
#+end_quote

#+begin_quote
古者富貴而名磨滅，不可勝記，唯倜儻非常之人稱焉。

蓋西伯拘而演周易；仲尼戹而作春秋；屈原放逐，乃賦離騷；左丘失明，厥有國語；孫子髕腳，兵法修列；不韋遷蜀，世傳呂覽；韓非囚秦，説難、孤憤。詩三百篇，大底聖賢發憤之所爲作也。
#+end_quote

#+begin_quote
此人皆意有所鬱結，不得通其道，故述往事，思來者。及如左丘無目，孫子斷足，終不可用，退而論書策以舒其憤，思垂空文以自見。
#+end_quote

** 究天人之际，通古今之变，成一家之言

#+begin_quote
僕竊不遜，近自託於無能之辭，網羅天下放失舊聞，略考其事，綜其終始，稽其成敗興壞之紀，上計軒轅，下至于茲，爲十表，本紀十二，書八章，世家三十，列傳七十，凡百三十篇。亦欲以究天人之際，通古今之變，成一家之言。
#+end_quote

** 豈有悔哉

#+begin_quote
草創未就，會遭此禍，惜其不成，是以就極刑而無慍色。僕誠已著此書，藏諸名山，傳之其人通邑大都，則僕償前辱之責，雖萬被戮，豈有悔哉！然此可爲智者道，難爲俗人言也。
#+end_quote

#+begin_quote
且負下未易居，下流多謗議，僕以口語遇遭此禍，重爲鄉黨所戮笑，以污辱先人，亦何面目復上父母之丘墓乎？雖累百世，垢彌甚耳！

是以腸一日而九回，居則忽忽若有所亡，出則不知所如往。每念斯恥，汗未嘗不發背霑衣也。
#+end_quote

#+begin_quote
身直爲閨閤之臣，寧得自引深臧巖穴邪？故且從俗浮沉，與時俯仰，以通其狂惑。今少卿乃教以推賢進士，無乃與僕私心剌謬乎？
#+end_quote

** 《太史公》牛马走司马迁

#+begin_quote
今雖欲自彫瑑，曼辭以自飾，無益，於俗不信，適足取辱耳。要之，死日然後是非乃定。

書不能盡意，略陳固陋，謹再拜。
#+end_quote

** 总结
#+begin_quote
明述作之本旨，见去取之从来。

--（清）章学诚
#+end_quote

#todo

* 写在后面
#+include: "../footer.zh.org"

* Footnotes

[fn:1] 本纪、表、世家、书、列传

[fn:2] 气势雄伟

[fn:3] 飘逸不可测

[fn:4] 后世人称韩愈的文章雄而不逸，欧阳修的文章逸而不雄，而他们得其一法就可成为当时的散文大家。

[fn:5] 中国有六家分别是：阴阳、儒、墨、名、法、道德

[fn:6] [[https://zh.wikipedia.org/wiki/%E5%B7%AB%E8%9B%8A%E4%B9%8B%E7%A5%B8][巫蛊之祸]]

[fn:7] 经天纬地曰文
