:PROPERTIES:
:ID:       211f6150-3917-44df-9ca4-558f739ac218
:END:
#+startup: showall
#+options: toc:nil

* 读太史公自序--什么是中国的责任

# todo

#+toc: headlines

#+begin_quote
大学之道，在明明德，在亲民，在止于至善。

--《大学》
#+end_quote

# todo

** 何为序

自序在一本书里面，占据着非常重要的地位。什么叫做“序”？ 我们过去看过许许多多现代著作中的“序”，在我们今天序的习惯，通常是指放在一本书最前面的那一篇，有时候是自己写的序，有时候叫别人写的序。那么如果是自己写的序，通常一开始这个序就是在谈作者说我为什么要写这本书，我从什么时候开始有写这本书的念头的，谈一谈我的感想，再谈一谈我要感谢谁，这样序的写的方式基本上没有问题。但是古书的序，远远不止如此。《史记》的序到底要怎么去理解它呢？

对于“序”这个字解释得最好的是吕思勉，他清楚地告诉你 “序”这个字有两个意义：第一个意义是“序者，绪也”，序就是端绪的意思，要做一个学问，最重要是像理一团乱丝一样。“绪”字像编织去理一团乱丝一样，最重要找到它的端在哪里，线头在哪里。找到了线头在哪里，你才能把一团丝给理清楚，这个就叫做“得其端绪”。读书也一样，所有的书里面可以包罗万象，但只要作者是头脑清楚的，他必然有他的端绪，他常常会把那个端绪写在他的序里面，帮助后来的读者用最简单明白、最快捷的方式，明白我这本书到底要说什么。第二个意义吕思勉说“序者，次也。”，就是次序的意思，一本书中间会包含着很多篇，就是包含着很多章节，你的章节要怎么安排，你先要谈什么，后要谈什么，在每一章底下你每一节的先后次序又是什么，这种东西就代表了作者对于全书的架构，对于全书整体的认知。因此在读任何一个头脑清楚的作者写的书，你们都必须重视它的目录，因为这个目录就代表了全书的基本架构，从目录去认识一个书的整体是最快捷的方式。所以《史记》这本书里面它的序，吕思勉的理解就包含两个意思，一个是所谓的“端绪”，也就是今天一般我们常说的“序”的意思; 一个是所谓的“次序”，就是我们今天所说的“目录”的意思。因此《史记》中的序就包含着今天所谓的“序”跟“目录”两者合一的功能。但是不管是序还是目录，对于一本书这都是非常非常重要的事情，你要了解这一本书必须从序这一篇开始。

所以章学诚说“明述作之本旨，见去取之从来。”，一篇好的序，特别是太史公之序要告诉我们述、作。一本书通常有“述”有“作”，“述”是因袭前人的部分; “作”是作者创新的部分。任何一本书都不可能有述无作，也不可能有作无述。如果有述无作，这本书就不成其为单独的一本书，因为作者完全没有加自己的意见上去，他只是把旧的书重新抄袭了一遍而已。如果只有作，任何一个文化都不可能是无中生有的，你能作一本书，必然是你有相对的文化基础，所以叫述、作。“明述作之本旨，见去取之从来。”，什么叫做“去、取”？ 史书和史料不同，任何一本史书，都不可能把所有的史料完整地抄录在里面，否则这本书就会变成流水账，这本书就会杂乱，让人不明白这本书重要的要点在哪里，因此任何一个史学家对于史料都必须有去有取; 去的部分就是删的部分，取的部分就是留下来的部分，从去取之间，才能看出一个史家的功力究竟何在，而史家通常会将他去取的原则，也明白的写在他的书里面，这叫“见去取之从来”。前面是引了两人的话简单说序是什么意思，就是“述一书之体要”，一篇序最重要是要把这本书的体，就是它的整体结构，它的要点，包括他为什么要写这本书，读这本书要注意哪些要点，通通会写在序里面。从这个观点出发，从各个角度来看，《史记》的《太史公自序》是一篇非常成功的自序，要了解《史记》就一定要读《太史公自序》。《太史公自序》除了在《史记》之中它占有极重要的地位以外，它本身的文字在中国国史上也有很重要的地位，在过去《太史公自序》被前人推崇为三大名序之一，这三大名序是：《太史公自序》、《说文解字序》、《文献通考序》。 而最早也最著名的正是《太史公自序》。 所以读史记需先从《太史公自序》开始读起，不管是就这篇本身的文学价值，还是在读懂《史记》上的意义来说，它都占有非常重要，无可取代的地位。

** 如何培養孩子？

#+begin_quote
太史公既掌天官，不治民。有子曰遷。[fn:1]

遷生龍門，耕牧河山之陽。年十歲則誦古文。

二十而南游江、淮，上會稽，探禹穴，闚九疑，浮於沅、湘；北涉汶、泗，講業齊、魯之都，觀孔子之遺風，鄉射鄒、嶧；戹困鄱、薛、彭城，過梁、楚以歸。

於是遷仕為郎中，奉使西征巴、蜀以南，南略邛、笮、昆明，還報命。
#+end_quote

这一篇文章完整的篇题是《太史公自序第七十》，什么意思呢？ 难道《史记》有70篇自序不成？ 当然不是，“第七十”代表他是列传体70篇列传中的最后一篇，而《太史公自序》除了本身是全书之序之外，它同时也是70篇列传中的最后一篇。为什么它是70篇列传中的最后一篇呢？ 因为太史公在这篇中，除了把全书的体要讲述一遍之外，他这一篇文章同时也是替自己作列传，因为他是替自己作列传，因此他把自己排在了70篇列传中的最后一篇。所以读《太史公自序》的各位必须注意 这一篇文章同时兼具两个性质：它既是全书之序，也是作者本身的自传。

“太史公既掌天官，不治民。有子曰迁。”，太史公其实在汉代正式的官称是太史令，太史令这个官职在汉代它所执掌的正职是负责天文、历算、祭祀之事。它主要管的是天文、历法，所以这里才告诉你“太史公既掌天官，不治民”，他不是一个治民之官，而他这里的“太史公”指的是司马迁的父亲司马谈。《史记》这本书是由司马谈和司马迁父子两代之力相继传述而成。“有子曰迁”，他的儿子叫司马迁。

接下来是司马迁的自述，“迁生龙门”，司马迁出生在龙门这个地方。“耕牧河山之阳”，从耕牧可以看得出来司马迁的小时候是且耕且牧，既从事农业的事业也从事畜牧的事业。否则一旦气候变化家庭的生计就很难保障。“河山之阳”，这是中国文化的基本常识，山南水北叫做“阳”，山北水南叫做“阴”，所以河山之阳指的就是山南水北的地方。“年十岁”，我们接下来要特别注意，你看看司马迁这样国史上如此了不起的人物，究竟他父亲是怎么教育栽培他的。“年十岁则诵古文”，司马迁十岁的时候就竟能背诵古文，什么叫古文呢？ 汉代所谓的“古文”特别在西汉武帝以前，往往指的是先秦的典籍文字叫做古文。

“二十而南游江、淮，上会稽，探禹穴”，二十岁的时候他就开始出去巡游天下，中国古人相信“读万卷书不如行万里路”，这是非常重要的事情，你没有实际的见识和历练，光靠纸面上的文字是绝对不够的，即使你很聪明。司马谈深知这一点，所以他栽培他的儿子目的不是要他做一个书呆子，目的不是要他做一个纸面上的学问家，目的是要他能把他读的东西和实际相以结合，你既然已经读过天下之书，当然希望你能见识天下各个地方。他第一站选择的是南游江淮，到楚国去，“上会稽”在今天的浙江，看看大禹当年在这里所留下的古迹是什么样子的。“窥九疑，浮于沅湘”，九疑和沅湘都在今天的湖南地区。“北涉汶、泗”，汶泗是什么地方呢？ 汶泗在古代就是所谓的鲁国的区域，也就是孔子的家乡，在今天的山东地区。“讲业齐、鲁之都，观孔子之遗风。”，他特地要到孔子的家乡去看一看，看看孔子过世之后，历经春秋、战国、秦到今天西汉，他当地的遗风到底是什么样子的，读书不如亲眼目睹，而他当时把他在孔子家乡的见闻，完完整整写在《孔子世家》最后的“太史公曰”之中。“乡射邹、峄；戹困鄱、薛、彭城，过梁、楚以归。”，在湘、苏这个地方绕了一圈之后，最后再经过了汉代的梁国楚国也就是今天的河南湖北地区，最后终于回到了关中。

“于是迁仕为郎中”，巡游天下之后回来就当上了郎中，郎中是随侍在武帝身边的官，而后武帝很快地就派他奉使到外面去，他开始出去奉使又到了什么地方去呢？ 书上的文字写“奉使西征巴、蜀以南，南略邛”，下面这个字有两个读音，有人念zé有人念zuò，各有道理，我们在这里先姑且念zé。“南略邛、笮(zé)、昆明，还报命。”，你看他接下来在巡游了整个东方六国，大致上在黄河以南的地区之后最后回到了关中，接下来要到今天的四川云南一带整个西南地区又去了一趟，即使在当时能够如此壮游天下的人也少之又少，为什么？ 因为尚游天下是要花很多的钱，如果没有司马谈全力支持，他在20岁之前还没有工作的时候，很难(能)够做这样的行为。这就是司马谈对司马迁的栽培计划，年十岁而诵古文，二十则壮游天下。司马迁一共有两个老师，一个老师是跟随学古文的孔安国，另外一个老师是跟随学《春秋》的董仲舒，孔安国跟董仲舒都是当时天下学问最大的人。想要栽培子弟是每一个人共同的愿望，做父母的人没有不希望子弟成才的，可是子弟成才得很少，你们就得问为什么。你们在读了上面这一段以后就要想，太史公的父亲也就是另外一个太史公司马谈，是怎么教育栽培他儿子的？ 他的儿子后来在学术上的成就，在中国国史几千年上也少有人能够比拟，可见这样的教育是无比成功的，那为什么他教育他儿子能成功，而我们今天教育儿子成才的却很少，他的关键在哪里？

很简单，我们一般中国人都喜欢说“望子成龙，望女成凤”，可以很肯定的告诉各位，那是没有用的，为什么？ 因为望是没有用的，想要儿子(女儿)成龙成凤要教子成龙、教女成凤，不是望子成龙、望女成凤。要望人人都会望，从小望到大你望的事情有几件实现了？ 教子成龙、教女成凤，教要得其法，不能不得其法，不得其法也难成功，而要得其法，最浅近的(方法)是：第一点，做父母的人身教重于言教，司马谈是什么样的人，他的一举一动一言一行，当然会影响他自己的儿子司马迁，所以身教比什么言教都重要，光是跟儿女用讲的是没有用，那叫“望”，什么叫做“教”？ 具体力行才叫做“教”。中国人教孩子识字，按传统大户人家世家的规矩，通常一般大户人家是6岁开始教孩子识字，识的第一个字就是“孝”字，一定从“孝”开始教起，这就是中国古代的文化教育。跟我们今天小学第一课教“天亮了，大猫叫，小狗跳”是完全不一样的教育方法，当然孰优孰劣、孰利孰弊，各位自有智慧不需要多言。教孩子第一点是父母身教重于言教，可是不是每个父母都那么杰出，就算有杰出的父母也很难教自己的孩子，这是天性，孩子听父母的话是很少的。那么第二点就是为你的孩子找好的老师，好的老师比一切都重要，司马谈深知这一点，他当时帮他儿子找的老师是孔安国跟董仲舒，在西汉一代，在学问上，在品德上，你很难找出比这两位更加杰出的人物，这就是他为他儿子教育所做的努力，我们从后来司马迁的成就来看，至少在学术和思想上，这样的教育是非常成功的。

司马迁出使西南以后回来报命，你出使西南之后必须回来，向天子呈报你这次出使的结果到底怎么样，这叫做“报命”。

** 漢武帝的封禪

#+begin_quote
是歲天子始建漢家之封，而太史公留滯周南，不得與從事，故發憤且卒。而子遷適使反，見父於河洛之閒。

太史公執遷手而泣曰：「余先周室之太史也。自上世嘗顯功名於虞夏，典天官事。後世中衰，絕於予乎？汝復為太史，則續吾祖矣。
#+end_quote

“是岁”，这一年刚好是元封元年，既然叫“元封”，你们就知道跟封禅有关系，这一年汉武帝要去实行封禅。“天子始建汉家之封，而太史公留滞周南，不得与从事”，汉武帝要到泰山去封禅，“封禅”是历史上的大事，我没说“封禅”是天下或国家的大事，那不足以形容封禅的重要，“封禅”是历史上的大事，一旦实行封禅，就代表向天宣告“太平盛世”的来临，所以历史上的封禅次数在古代不多，能够参加封禅的人几百年、几十年都未必能够碰到一次，可能要等待非常多代，刚好在你这一代你才能够参与这个盛会。可是什么叫做“封禅”？ 用最简单的比喻，其实我们所谓的“天子”，严格来说他并不是这个天地中的主人，用现在的公司组织来说，“天子”是代“天”来掌管这个天下的，他其实只是总经理，“天”才是董事长，于是“天子”在业务做到一定程度的时候，他可以决定是不是要跟董事长报告目前的业务成果，那么董事长如果听见你业务很好，就会对你有所福报，董事长如果觉得你业务不好，就会降下灾祸，那你可能就被免职了。那问题来了，如果你是总经理，你会挑业绩好的时候去报告，还是挑业绩不好的时候去报告？ 我想大部分人都一定会挑业绩好的时候去报告，没有人想要去触个霉头吧。所以封禅举行的时候，必然是天子觉得天下已经太平了，我必须要向上天报告这个事情，为什么要报告？ 它里面含有很多层用意，在中国古代文化真正的思想中，他们觉得“封禅”这个东西真正的意义是“为民报德”，什么叫做“为民报德”呢？ 就是上天赐下老百姓这么多东西，现在天子把天下治理得这么好，我们要举行一个典礼来感谢上天，让上天知道天下现在有多好，我们对它的感激之心有多么强烈。那么问题来了，武帝的封禅是这么回事吗？

武帝的封禅不是那么回事，在武帝即位到现在，他与匈奴征战多年，天下穷困，黄河发大水，山东发饥荒，天下苦于战祸，可是武帝还是要实行封禅，为什么在这个时候他要实行封禅呢？ 因为他希望得到上天的福报，方士们告诉他，想要求长生就必须行封禅，为此他所做的行为就(是)要实行封禅。这场封禅典礼真正的目的，在司马谈来看，纯粹是为了求仙得长生，而不是为民报德，而他这样的意见不断地表达出去，让武帝觉得这个人非常碍眼，于是决定封禅绝不带他去，否则当面有一个人老是在告诉你，这个错那个错，这个汉武帝怎么受得了呢。和封禅最有关系的几个官中掌管天官的太史公必然是其中一个，那为什么在这样的旷古大典中，身为太史令的司马谈却不能参加。原因只有一个，谁能让司马谈不能参加？ 他应该参加谁能让他不参加？ 唯一能让他不参加的就是汉武帝。

所以你们注意看“太史公留滞周南，不得与从事，故发愤且卒。”，有的讲《史记》的认为把这两句话解释成，太史公在当时因为刚好生病，所以不能参加这个事情，这样的解释是有问题的。为什么？ 你从这句的前后文来看，有个“故”字，“故”就是“因为上面那样，所以才这样。”。是因为“留滞周南”，就在洛阳这个地方，“不得与从事”，所以才“发愤且卒”。绝不是因为“发愤且卒”，所以才“留滞周南 不得与从事”，这在文章里的脉络是清清楚楚的，除非你要告诉我司马迁记错了，连他父亲怎么死他都记错了，否则的话，你就只能够根据这个文章的脉络往下追寻。因为“留滞周南，不得与从事”不能参加封禅，所以发愤且卒。

第一点：这样的旷古大典能够参加是当时所有读书人、所有官员、所有最上层的精英最荣耀的事情，错过这一次就不知道等待多久才能再碰到一次封禅大典，因此司马谈不能够参加这场封禅大典对他来说是很大的遗憾。光是如此还不止，更重要的是他对武帝忠心耿耿，他眼看着汉武帝要去进行一场错误的封禅典礼，这场封禅典礼的目的在求仙，有根据吗？ 整篇《史记·封禅书》都在写汉武帝求仙求长生的经过。

第二点：汉武帝这场封禅大典非常特别，如果真的是“为民报德”的话，照理这场封禅大典应该是文武百官，重要的官员都要能够参加，可是汉武帝到了泰山之后，身边只带了他最亲近的一个人，他最喜欢的这个人一起上山求封禅。这个人是谁呢？ 这个人是霍去病的儿子，武帝把他的儿子(调)到皇宫来当戍卫，跟在他身边，这次封禅大典谁也不带，就带他的儿子上山，武帝对他的儿子够宠爱的吧。他们两个在山上怎么进行封禅大典的根本没有人知道，如果这个封禅是个公开仪式，为什么不带人上山？ 为什么不让人知道他在山上怎么封禅？ 那必有不可告人之处，那个“不可告人之处”从《封禅书》来看必然和武帝想要求仙、求长生，和方士的建议是有关系的。可能你们会感慨，至少霍去病的儿子是真得获武帝信任的，说实话什么叫做皇帝的信任？ 霍去病的儿子举行完封禅典礼下山不久之后，就暴毙身亡，他的儿子年纪还非常轻，怎么会这样就“暴毙身亡”了呢？ 因为武帝在山上的秘密不能让其他人知道，这就是皇帝的宠爱，你们要明白这个事情。

继续讲“不得与从事，故发愤且卒。”，“且卒”就是快要死掉了还没死，如果已经死掉了，司马迁回来就跟他父亲说不到话了。就在他快要死掉的时候，“而子迁适使反”，子迁刚好到南边去出使，刚好就回来了，就在这个时候，“见父于河、洛之间”，原本他到四川、云南去是应该回到陕西的长安去报命，可这个时候武帝刚好到到山东的泰山去封禅，他要报命只能从这个地方再到山东去，中间会经过洛阳，所以才会“见父于河、洛之间”。注意看下面这一段，这一段是非常重要，也是极为精彩的一段，整个《太史公自序》以此段为核心，你们要读懂这一段才知道太史公为什么要写《史记》。

太史公司马谈“执迁手而泣曰”，抓着他儿子的手哭泣地说，说什么呢？ “余先周室之太史也”，我们的祖先原本是周朝王室的史官。“自上世嘗顯功名於虞夏”，更久远的时代就已经彰显他的功名，也就是从唐尧、虞舜到了夏禹的时候，一路这样承接上来。“典天官事”，当时最早的时候就是做天官这个职务，但是司马迁这样辉煌的祖先功业，到了后来就中断了，他们家原本是天官，后来失掉了天官的官守，后来成为史官，后来又失掉了史官的官守，而后隔了这么多年，这么多世代，终于他的父亲司马谈又重新当上了太史，所以他才说“后世中衰，绝于予乎？”。为什么司马谈要这么说呢？ 因为他重新当上了太史，他的祖先是太史，如今在中断了这么多世代之后，他又是太史，他有心想要发扬他祖先的功业，可是问题是他现在要死了，他的事业还没有完成，什么事业？ 史官的事业。他说“汝复为太史，则续吾祖矣。”，他跟他的儿子说，你如果再做上太史，就能把我们祖先的功业继续接续下来，那我们这个史官的事业就不会到我这一代中断了。司马谈的这个观念，完全是一个中国古典时代那个大文化传统的遗续，那种把祖先家族的事业当成是自己的责任，自己不能让祖先的功业毁在自己的身上，这就是司马谈真正向往的。可是做大事业按曾国藩的说法，做大事业以找替手为第一要义，什么叫“找替手”？ 就是找寻接班人，继承人为第一要义，任何的大事业，都没有一代一人能够成功的，人的命数不是自己能掌握的，你想要事业不随着你的命数而中断，你就必须在一开始就准备找好接班人，这样的接班人跟继承人，不一定能够碰得上，那该怎么办？ 司马谈的做法是那就自己栽培一个，所以他从小让他的儿子“年十岁则诵古文”，求教于天下名师，二十更壮游天下，正是为了有一天，他不在了以后，他的事业可以交给他儿子继续做下去。

** 什麼是責任？

#+begin_quote
今天子接千歲之統，封泰山，而余不得從行，是命也夫，命也夫！余死，汝必為太史；為太史，無忘吾所欲論著矣。
#+end_quote

“今天子接千岁之统”，为什么讲“接千岁之统”？ “千岁”并不是一个准确的一千年，只是一个概数，中国古代写东西，有的是实数，有的是概数，不要拘泥于文字。从周能够一统天下，让天下太平没有战乱，之后经历了春秋战国，天下无王，没有天子来维护天下的秩序，自然就没有人能来封禅。到了秦的时候，秦虽然统一天下也去封禅了，但是秦以暴虐治天下，他不是所有人共同所承认的天子，于是到今天，西汉初年战乱，经历文景休养生息，而后到了武帝，终于天下太平了，武帝觉得这时候可以实行封禅了，而这期的封禅，倘若秦的那次封禅不算的话，距离上一次的封禅已经非常遥远了，武帝实行封禅，无疑地是告诉天下，这个千岁的正统，已经被他接续上去了，所以告诉你“今天子接千岁之统，封泰山”。

做这么重要的事，“而余不得从行”，注意“不得从行”。就从“不得”这两个字来看，你们觉得司马谈是自己不想去封禅，还是他想去(而)不能去封禅。“不得”当然就是不能，不是不愿，不是不想，是他不能够去从行，他很想去从行，不能去从行的结果是什么呢？ 他不敢怪天子，他只能够怪命，“是命也夫，命也夫！”，这是命中注定的事，是命中注定的事，谁也没有办法，他是太史令，是执掌天官，与封禅最有关系，他家曾经祖先有那么辉煌的功业，对他来说参加这个接续千岁之统的封禅大典是生命中何等重要的事，可是就当这东西出现的时候，他没有办法参加。

“余死，汝必为太史。”，这句话非常非常重要，司马谈告诉他儿子，我死了你一定能成为太史，你们听到这句话为什么重要，你们要特别注意一件事，汉代的太史令不是世袭，汉代的太史令是由皇帝任命的，上一任太史和下一任太史之中没有必然的关系，因此司马谈在这种制度之下，他敢肯定地告诉他儿子，我死了以后你一定是接着我做太史的那个人。司马谈何以有这样的自信，原因是他深知太史是一门专学，他环顾天下，即使持平而论，再也没有一个人能比他儿子更有资格担任太史之工作，而武帝虽然种种作为司马谈并不赞成，但是武帝的眼光，看人的眼光，还不至于坏到这个地步，所以他非常有把握，以他儿子的才学，武帝在他死之后，必然会选择他的儿子继任太史的功业，这就是司马谈的计划。他一步一步地栽培他儿子，到这一刻他终于有自信地说“余死，汝必为太史。”

可是做太史，不是叫你来享受的，做太史是叫你来尽责任的，他就告诉你“为太史，无忘吾所欲论著矣。”，你千万不要忘了我想要论著的那本书。那本书是什么书，那本书就是各位现在正在读，眼前看到的《史记》这本书。他父亲死之前，没有交代他儿子要怎么处理房产，没有交代他儿子当官的秘诀，没有交代他儿子其他的事情，唯一交代的事情就是你要把《史记》给完成了，为什么？ 你们要明白一个事情，当一个老师的人其实什么都可以讲，但是有的东西就算努力教，也不一定在今天能教得会同学了，并不是因为这个文字特别难，文字难可以慢慢讲解，文字背后的东西我们可以细细追寻，真正难教的事情是古人有的观念，今天已经完全没有了，也不能接受了，这种情况之下，你要把古人的那个观念跟今天的人讲清楚就特别特别难。这观念到底是什么观念呢？ 就是“责任”两个字，中国古代的人是为了责任而活，他们相信自己身上有责任。

什么是“责任”？ 就是天下有一件事情，做了对你没有好处，你的人生也很难从中得到真正的快乐，可是你非做不可，那就叫做责任。为什么“责任”这个东西难教呢？ 因为现代是一个个人化的时代，既然做了这个事情未必快乐，既然做了这个事情纯粹是付出没有获得，那为什么还要去做它呢？ 人生是自由的，我大可不要去做它，我可以不用选择这样的一条道路啊！ 但是当你的人生成长到今天，你从小长到现在，是因为有其他的人为了你而在尽责任，在付出一切让你能够享受，今天我们能享用这样美好的文明成果，我们的国家没有战乱，能够富强，是因为前面有无数的先圣先贤先烈们努力地前仆后继，牺牲他们的人生和理想，来替我们付出了，来让我们获得，所以我们能长到今天，享受这么多东西，是因为有无数的人付出的结果，他们尽了他们的责任。有的年轻人会说，他觉得他的父母不了解他的理想，不接受他的理想。那就要问各位，难道你的父母没有理想吗？ 他们是为了谁牺牲他们的理想，最后一辈子这样辛苦努力，看别人的冷眼，看别人的脸色，也要努力把这个家维持下去，要能够教养你长大成人，他们是为了谁付出，他们是为了谁牺牲他们的理想，没有说要你们一定要按照你们父母说的话去做，这是你们的人生，你们当然有自由选择的权利，可是你们起码要尊重那个为了你牺牲他们自己理想的人吧！ 接受不接受中国古代的观念在你自己的判断，那是你的自由，可是你起码要尊重那些尽了他的责任，而付出无数血汗努力的人吧！ 这就是中国传统文化教育要告诉你们的东西。如果你真的读懂了中国古书，你就会发现中国古书里面没有教升官，没有教发财，它从头到尾教的只有“责任”这两个字。什么是你的责任？ 如果前人都为了你的人生，付出了无数他们自己的努力，尽了他们的责任，而到了你这一代，你说我要追求个人的快乐，我不要尽责任了，那我试问你，下一代要怎么办，以后的人类社会要怎么办？ 一个人接受别人那么多东西，到了换他成为付出的责任的一代，他却吝于付出，我认为人类文明最大的危机莫过于此，而今天我们重新回到两千多年以前，去看待司马谈和司马迁临终托付的这一幕，他从头到尾讲的正是“责任”两个字，他告诉他儿子的就是：到今天我把责任传给你了，你务必要把这个责任给我尽到。

** 中國史學的危機

#+begin_quote
且夫孝始於事親，中於事君，終於立身。揚名於後世，以顯父母，此孝之大者。

夫天下稱誦周公，言其能論歌文武之德，宣周邵之風，達太王王季之思慮，爰及公劉，以尊后稷也。幽厲之後，王道缺，禮樂衰，孔子修舊起廢，論詩書，作春秋，則學者至今則之。
#+end_quote

那么司马谈要托付给司马迁的责任到底是什么呢？ “且夫孝始于事亲，中于事君，终于立身。”，“孝”的开始是怎么侍奉你的双亲，它的最后最高的境界是“立身”，“扬名于后世，以显父母，此孝之大者。”，这是《孝经》的文字。什么是“孝之始也”？ “身体发肤，受之父母，不敢毁伤。”这是“孝之始也”。父母把这个干干净净的身体生了给你，你为什么要去损伤玷污这个身体，你损伤(玷污)这个身体岂不是让父母伤心，他生了你不是为了让你来做这样的事情的，你让父母伤心，这不就是一开始的“大不孝”。可是“孝”的最高境界不是这个，如果按照前面那个境界，你就会说那这些成仁取义的烈士岂不是个个都是“大不孝”吗，当然不是。中国的文化讲究“层次”，每一个“层次”在它的“层次”之内有它的准则，可到了更高的“层次”有更高的准则。在中国古代人来看，还有比前面这个“孝之始也”更大的东西，那就是“立身(行道)，扬名于后世，以显父母”，让天下的人都知道，你的父母教出了这么了不起的孩子，对父母而言，没有比这个更大的荣耀了。所以按中国传统文化，一个真正的中国人，当别人夸奖你得到什么成就的时候，他第一件事必然绝对不会说是因为他自己的缘故，第一件事必然是归功于他的父母，这是中国传统文化的孝道，没有父母就没有你今天的成就，所以一定是把自己的成就归功到父母身上。而这里 司马谈就告诉他儿子，我最希望你做到的是“立身扬名于后世，以显父母，此孝之大者。”，让后面的人都记得你有这么一个了不起的儿子，是什么样的父母造就出这样的儿子来。司马谈这个临终愿望成功了没有，你们知不知道司马迁这个人，你们知不知道司马迁的父亲叫司马谈，如果你们都知道，在隔了两千多年历经了无数战乱，历经了文明这样的巨变之后，我们都还知道这本书，都还知道这本书的作者父子二人，那么司马谈的托付就是成功的。

“夫天下称颂周公”，为什么天下要称赞周公，颂扬周公，不止是因为周公个人的功业，天下把他个人的功业还看在其次，更高的是他个人的功业能够继续发扬他父祖的事业，所以“言其而论歌文、武之德”，这就是光扬父兄之德，光扬祖德。“宣周、邵之风，达太王、王季之思虑，爰及公刘，以尊后稷也。”，一层一层地推上去，从他的父兄推到周的始祖去。“幽、厉之后”，你看文风一转，周公有这么大的功业，可是天下没有什么功业能永远保存下去的，所以“幽、厉之后，王道缺，礼乐衰”，礼坏乐崩，周公治理(的)卓越的事业，周氏的功业到幽厉之后就整个中衰了。周氏的事业中衰，不代表中国的文化中衰，这个文化在周公之后出了非常了不起的人物，这是中国历史上最伟大的人物没有之一。这个人物就是孔子，“孔子修旧起废”，什么叫“修旧起废”？ “旧”和“废”指的都是孔子以前中国承传已久的古典文明，那个辉煌灿烂绵延长久的古典文明，到幽厉之后已经逐渐在走下坡，已经逐渐崩溃，当时的人一天一天的不断地放弃这个文明里的东西，于是孔子希望能够“修旧起废”，把这个古典文明的精华，透过他个人的努力，重新发扬让它能传承下去。“论《诗》《书》，作《春秋》，则学者至今则之。”，修旧起废具体的作为就是“论《诗》《书》”，“论”就是“录”的意思，能够把原本古《诗》《书》的很多篇，孔子从里头选取精华把它摘录出来，而成为孔子自己修的《诗》和《书》。另外他还“作《春秋》”，古文家心中的《春秋》不过是把旧史书重新加以修撰，重新加以抄录而已，所以在古文家的心中《春秋》是一部史书。可在今文家的心中，特别就是后来在汉代所谓的最主流就是公羊家的心中，《春秋》不只是一部史书，它里面寄托了孔子让天下人群，从据乱世、升平世到太平世，三世进化之治道与治法，孔子怎么样从头建设一个国家，怎么样让这个国家一步一步做到“天下太平”，里面的根本道理和方法全部写在《春秋》之中，所以才说“孔子作《春秋》，则学者至今则之”。到了西汉那个时候，天下学者多半都还忠法孔子，就因为孔子有这样的大功。

#+begin_quote
自獲麟以來四百有餘歲，而諸侯相兼，史記放絕。
#+end_quote

“自获麟以来四百有余岁”，这里的“获麟”指的是春秋的最后一年，鲁哀公十四年，“鲁哀公西狩获麟”这件事情。因为“鲁哀公西狩获麟”，所以孔子因为这样事件的触发，才决定要写《春秋》。过了两年孔子就死了，那么孔子一生最后的遗著就是《春秋》。所以“获麟”这件事情就代表了“孔子著《春秋》”这件大事，所以司马谈才说“自获麟以来四百有余岁”。为什么他要说“四百有余岁”，因为“四百有余岁”这个数字是错的。曾经有学者严格计算过，从鲁哀公十四年到汉司马谈死的这一年才三百七十二年，怎么能说是四百多年呢？ 怎么能说“四百有余岁”呢？ 所以司马谈记错了。那问题就来了，如果司马谈记错，司马谈是天官，是管天文历数的、管历法的，司马谈是史官，在当时的天下，任谁都有可能弄错年份，最不可能弄错年份的不就是司马谈吗。就算司马谈病糊涂了，他的儿子司马迁没有病糊涂，如果“四百有余岁”是没有异议的，司马迁会刻意在这里记一个错误的数字吗？ 这都是不合常情常理的。所以读中国书有时候不能“泥文生义”，不要拘泥于文字，最后就自然地去说古人错了。这里“四百有余岁”司马谈是刻意这么说的，他想要在这一句话里面寄托一个什么样的东西？ 他为什么要明白地去说一个明显年数是不合的数字？ 因为这是有意义的，后面会谈到。

“而诸侯相兼，史记放绝。”，春秋战国时代不断战乱，各国原本都有太史的传统。很出名的就是“崔杼弑其君”、“赵盾弑其君”的典故，崔杼在当时弑了他的君主，齐国的太史就把这个事情写下来，写“崔杼弑其君”，于是崔杼就把齐国太史给杀了，杀了太史之后，他的弟弟继续接上来，继续担当太史，前仆后继，最后崔杼杀不胜杀终于屈服，他就说 “那你就写下来吧”。 为什么呢？ 第一点：从这个故事里可以明白，在当时周氏封建的时候，太史是家族内传承的，所以司马谈跟司马迁说他们的祖先“释典周氏”绝对不是空口说白话，也不是无中生有，这是当时的实际的情况。第二点：中国人为什么把“史学”看得特别高，从那个记述 “崔杼弑其君”、“赵盾弑其君”你们就会发现，它里面讲的是“其君”，史官讲的可不是“我君”或“崔杼弑君”，“其”是“你的”，崔杼弑“他的”君，赵盾弑“他的”君，从这个史官里的记述就知道，史官并不认为“他”杀的君是“我”的君，为什么？ 因为各国的太史在当时都是由周王氏派驻到各国去的，他们在家族内父子兄弟相承，可是他们是直接受命于天子，他们是直属天子的，因此在他们眼中，他们是代理天子到各国来记录史事的，所以中国的史官在当时，从一开始就培养(出)了他们超然于各国政治之上的地位，也就是因为这样，史官才有那样的文化使命感和责任感。那么继续看下去。

可在天下战乱了以后，各国的史官纷纷失其官守，在各国史官失其官守以后，各国的史书就因为这个样子逐渐地中断，到了秦统一六国之后 又刻意毁掉了六国的史书，只剩下《秦记》。这里的“史记”指的并不是我们今天眼前看的这本书，“史记”原本是中国古代史书的通名，我们把所有史书都叫作“史记”，可是后来为什么“史记”变成这本书的专名呢？ 因为这本书实在太了不起了，后来的人把这本书看得无比重要，认为它是中国史学最重要的代表，所以就以通名作为它的专名，这是后来的变化。而秦国的史书是六国当时天下史书之内比(较)差的一本，它记载太过简略，等到《秦记》到最后留下来根本不足以重修古代史书的需要，因此太史公在著书的时候，他有特别讲清楚，战国这一段的史料是特别缺乏与特别混乱。而它为什么会产生这样史学断裂的情况，就是因为“诸侯相兼，史记放绝。”，这个时候中国面对的是一个史学中衰的危机。从一开始就有非常好的史学传统，到后来我们也看到像《左传》、像《竹书纪年》，它们的特征都是年、时、季节、月、日记载得清清楚楚，不止时间记载得清楚，“史学”有几个要件：时、地、人、事也记载得清清楚楚，可到后来我们再去看《秦记》文字，《秦记》文字各位如果有兴趣的可以看《秦始皇本纪》最后的那个附录，它附录里面就是《秦记》文字，《秦记》的文字里面就只有事，连年都没有，往往就只有记一任国君，那任国君多少年死掉，那任国君(在任)里面发生什么大事，《秦记》比起《左传》，比起《竹书纪年》，那无疑是中国史学的巨大倒退，那是中国史学的中衰，中国的史学到这一刻如果没有人出来重新恢复旧的史学，中国的史学传统可能就此断裂。

** 他該如何抉擇？

#+begin_quote
今漢興，海內一統，明主賢君忠臣死義之士，余為太史而弗論載，廢天下之史文，余甚懼焉，汝其念哉！」

遷俯首流涕曰：「小子不敏，請悉論先人所次舊聞，弗敢闕。」
#+end_quote

经历了战国这样的战乱，史学即将中衰断绝，好不容易秦朝统一天下结束了六国的战乱，秦国因为力行法家统治，它们的统治者根本认为历史对于统治是有害的，所以才说禁止大家以古非今，“以古非今者族”，比“偶语诗书者弃市”还要严重，它非常非常厌恶史学，它刻意地在消灭中国的史学，所以中国的史学并没有因为秦朝统一天下而迎来了生机。好不容易“今汉兴，海内一统”，汉朝出来了，天下终于太平，老百姓可以休养生息，文化事业蓬勃发展，可是各位要明白一件事情，汉朝的复兴并没有代表史学的复兴，汉承秦制，它虽然没有像秦朝那样刻意地消灭史学，可是汉朝的统治者也绝对没有想要恢复史学，发扬史学的想法。有人说不对吧汉朝不是有太史令吗？ 可是秦朝也有太史令啊，问题秦跟汉的太史令都是不修史的啊。秦跟汉的太史令各位去查一查，秦跟汉的太史令是不修史的，他们管的是天官，管的是天文历算，管的是祭祀，他们和修史半点关系也没有。后来西汉的太史令司马谈和司马迁去修历史修出这部《史记》，那纯粹是个人兴趣，那纯粹是正职以外的私人兼差，那跟他们的正业半点关系也没有，在汉代太史令管的主要是术数、天文历算。太史令和朝廷沟通的职权的范围也基本上都跟天文历算有关。因此西汉的出现严格地来说，中国的史学只是没有继续被破坏下去，它并没有因此而复兴，因此司马谈在这一点上，他有强烈的忧惧和强烈的使命感，中国的史学即将断绝。

“明主贤君、忠臣、死义之士”有那么多，“余为太史而弗论载”，我担任太史却不能把这些“明主贤君、忠臣、死义之士”记下来，把这些值得记载在历史上的人物把他记载在历史之中，我有愧我的职守。这里讲的修史的这种职守是太史公司马谈的自觉，是他自我的使命感，和国家交代给他的工作半点关系也没有，汉代的史官是不修史的，他的正式职掌是管天文历算的，你们要特别明白这一点。而他之所以有这样的使命感，并不是因为朝廷要他这么做，而是因为他的祖先原本是史官，他有这样家族文化的大传统下来，而后他们有那么多代的祖先都没有办法担任太史，到他这一代他终于重新去当上太史了，他担任太史之后他私人想要恢复过去太史真正的职掌，也就是修史，这是司马谈的自我期许。他现在把这个期许交给司马迁，为什么我们非要修史不可，他清楚地告诉他这儿子，“废天下之史文，余甚惧焉”，因为如果你不把这个事业继续发扬坚续下去的话，我担心中国历史的大传统，中国史学的大传统就要从此断绝了，这是他最害怕的事，临终之前告诉他儿子“余甚惧焉”，各位觉得不能理解吗？

我们按今天的想法觉得，我不做这个也自然会有别人做这个的，答案是这样想当然有可能，可是可能终究是可能，这种可能性非常小。连横在写《台湾通史》的时候，在《台湾通史·序》里面有一段极其动人的文字，让人印象非常深刻。那段文字告诉你“修史难，修台湾史更难，尤以今日修台湾史最难。”，因为他写《台湾通史》的时候已经是日本统治台湾的时候了，他说我也知道我自己的才学是不够资格来写这部《台湾(通)史》的，可是我为什么非要写不可，因为我更清楚，如果我今天不写台湾史，以后再也没有人能做这个工作了，这就叫做“废天下之史文，余甚惧(焉)哉”。这是一种对于大文化传统的使命感和责任感，而这种使命感和责任感不只在连雅堂一个人的身上，在无数的中国读书人身上都有这样的使命感和责任感。在遥远的西汉时代，太史公谈就是以这个告诉他太史公迁的，环顾天下我们是最有资格来做这件事情的人，因为我们受过身为一个史官完整而良好的教育，环顾天下有使命感会来做的也只有我们，因为我们的祖先是太史，因为我们“责无旁贷”。既然讲责任，前面说过中国文化就是“责任”二字，讲责任就有“责无旁贷”这样的意义，你必须去想，如果你都不愿意做，别人为什么要做，如果你都觉得你不能做，还有什么人能比你更有资格来做，这就是中国人的责任感和使命感。中国文化之所以到今天没有断绝，正是来自于过去几千年，有无数的读书人有这样的使命感和责任感，所以这个文化没有断绝。

而今天在你们眼前的，是中国历史最危险的一刻，太史公谈和太史公迁觉得他们责无旁贷，跳了出来把中国的史学传统重新接续上去，因为有《史记》的出现，后来才有《汉书》，才有《后汉书》，有《三国志》，有无数的史书出现，中国的大史学传统终于恢复重新昌盛，这两个人在中国史学的生死存亡之际功莫大焉。“余甚惧(焉)哉”，我非常地害怕这件事，而我今天告诉你的目的是要“汝其念哉！”。什么叫做念？ 就是“念兹在兹”，你要把这件事情时时刻刻放到你的心上，无论如何一定要完成这本著作，让中国的史学不会就此断绝。如果司马谈跟司马迁讲了这段话以后，假想你们是司马迁，你们要怎么去回答你的父亲？ 父亲交给你的不是荣华、不是富贵，而是责任，你从小受了那么完整、良好的教育，在当时的人来说你的教育绝对是第一流的，正是为了这一天的来临，人生是可以选择的，你有你的自由，而在这一刻，你要选择承接这个责任，还是逃避这个责任，要承接这个责任，你会很痛苦，可是后世有无数的人会因为你而得到好处。如果选择放弃这个责任，你会很快乐，但是后世无数的人就会因为这样再也不知道中国曾经有那么优良的史学传统，他们会因此而很痛苦。人生的选择决定你是什么样的人，就在这一刻你该怎么办？ 我们来看看司马迁怎么办。

“迁俯首流涕曰”，把头低下去，整个泪流满面痛哭流涕，说“小子不敏”，这是自谦之词，告诉你我虽然没有你想象得那么聪明，“请悉论先人所次旧闻”，论就是录的意思，你从这里面就可以看得出来，司马迁在当时已经知道他父亲正在著作《史记》，而且已经有一部分是已经写好的，所以才叫“(请)悉论先人所次旧闻”，所以我才说这部书有两个作者，一个是司马谈、一个是司马迁。“弗敢阙”，我绝对不敢让史文在我这一代就此中断，我把这个责任完完整整地记下来了，这就是他对他父亲临终之前的誓言。而后来他为了这个事情付出了他的一生，而他也终于完成了这个事业。

** 小子何敢讓焉！

#+begin_quote
卒三歲而遷為太史令，紬史記石室金匱之書。

五年而當太初元年，十一月甲子朔旦冬至，天歷始改，建於明堂，諸神受紀。

太史公曰：「先人有言：『自周公卒五百歲而有孔子。孔子卒後至於今五百歲，有能紹明世，正易傳，繼春秋，本詩書禮樂之際？』意在斯乎！意在斯乎！小子何敢讓焉。」
#+end_quote

“卒三岁而迁为太史令”，他父亲过世后三年，果然像他父亲临终所预言的，司马迁当上了太史令。当上了太史令之后，虽然太史令的正职是管天文历算的，但是当太史令有个莫大的好处，是他可以看到皇家图书馆里的藏书，皇家图书馆就是当时所谓的秘府，是不对外开放的，一般人是看不到里面的书的，各地有献书都会收藏在秘府之中，而史公有这样的天独厚的条件，所以他说“䌷史记”，过去所有的史书“石室金匮之书”，“石室金匮”就是讲秘府中的藏书。

“五年而当太初元年”，太初元年这一年，发生了一件与国史有重大意义的事件，也就是改历法。“十一月甲子朔旦冬至，天历始改”，什么叫“天历始改”呢？ 在西汉武帝改历法之前，汉代主要都是秦朝的历法，秦朝的历法是以十月为一年的第一个月，而汉武帝这个时候重新改回了所谓的太初历，太初历是以正月为一年的第一个月，后来武帝改完这次太初历以后，这个太初历是为了恢复夏历。我们现在多半把中国的旧历法讲成旧历、讲成农民历、讲成阴历，讲旧历勉勉强强，但是讲农历或阴历实在是不适合的，第一点：阴历“阴”指的是月亮，可是中国古代的历法其实是阴阳合历，它既有月，也有日，所以不应该称它为“阴历”。讲农历可中国古代的历法也不是专门只有农人在使用，所有的人都在使用，士农工商都在用，因此它也不该称为“农历”，所以称为夏历是最好的称呼，因为“夏”的意思是“中国之人也”，这在《说文解字》中写得很清楚，夏历就代表这是中国的历法，而太初改历正是改为以正月为岁首的夏历，此后中国两千多年都沿用这个历法，基本都是用这个历法的架构了，所以叫“天历始改”。这里面还有很重要的影响，孔子有一个理想叫作“行夏之时”，应该用夏历来作为天下最好的历法，而这个时候到这一刻，这样的理想终于完成实现它了。参加“天历始改”这个工作，最重要的人物就是太史公司马迁，太史公就是管天文历算的，现在要修改历法，怎么能没有太史令的参加。而太史公司马迁参加这个“天历始改”的工作之后，“建于明堂”，“明堂”是传统文化里头布政教之所，公布政教的地方。“诸神受纪”，历法一改不是只有人受到影响，连神明也受到影响，因为神明所有祭祀的时间全部都要改，“诸神受纪”受睿纪，诸神都要接受这个瑞祭，祭祀全部都要改成新的历法，太史公在这一刻完成了这样辉煌伟大的事业，这个事业影响了之后中国两千多年。

他讲了一段话又讲了一段话“太史公曰”，这里的太史公指的就是司马迁。“先人有言”，这个先人指的就是司马谈，已经过世了。他说什么呢？ “自周公卒五百岁而有孔子，孔子卒后至于今五百岁”，特别注意这两段，这两段是什么意思？ 前面已经说过孔子到司马迁的时候绝对没有五百岁，连四百岁都没有，那为什么太史公在这里清楚地告诉你“孔子卒后至于今五百岁”，因为这里的五百不是一个实数，而是一个虚数，是一个概数。中国人相信五百年圣人出，每经过五百年就会有一个新的圣人出来重新带领天下之事业。而“周公之后五百年有孔子”，这个“五百年”不是准确的五百年，只是一个概数，代表一个新的圣人出来了。“孔子至于今五百岁”，太史公讲这句话的目的不是要告诉你孔子死了到现在刚刚好五百年，而是要告诉你孔子死了之后，天下没有圣人久矣，今天天下应该再有圣人诞生了，这是一种文化的使命感，天下如果没有圣人怎么办？ 那我们就必须去承接这个文化的使命，周公死了之后，天下无王无圣久矣，天下礼坏乐崩战乱，于是孔子自动自发出来承接了这个使命。而今天中国读书人前仆后继的精神又发挥了，司马迁又要再度出来承接这个使命，所以前面讲的“四百有余岁”就是因为要接续这里的“五百”，所以司马谈临终托付的时候故意要讲成“四百有余岁”，而不是准确地告诉你到底是三百几年。

到今天有没有一个人能够“绍明世”，“绍”就是继，能够重新接续过去那个光明美好的时代，那个大道苍冥之事。“正《易传》”，把《易传》中不正的部分都能把它正掉，“继《春秋》”，这里的“继”讲的是正面的继承。“本《诗》《书》《礼》《乐》之际？”，讲的还是一个正面的继承。各位请看上面这一段，《易》《春秋》《诗》《书》《礼》《乐》是不是刚好就是“六艺”，六艺是谁做的？ “六艺”在汉代人来看是孔子做的，起码是孔子重新整理的过去古典文明的辉煌成果，自己又重新加了自己的新意所做出来的书，而今天孔子到现在，有新的圣人应该出来了，就有人应该接续“六艺”这个中国古典文明，传承以下文化的大传统，而这里讲的“继”，讲的“本”，全都是正面继承，“绍”也是正面继承。那就有疑问了，第一点：那为什么《易传》这里要用一个“正”呢？ 原因是因为在中国的文化传统中，“易”往往有强烈的普世功能，可是孔子讲“不卜而已矣”，他重视的是“易”的义理，而不是“易”的普世，所以这里要“正”其不正。第二点：虽然“绍”是正面继承，“继”是正面继承，“本”是正面继承，可是哪一个是最直接的正面继承？ 程度最强烈的正是那个“继”字，正面继承《春秋》，所以我们后来才说《史记》继《春秋》是有它的道理的。

“意在斯乎！意在斯乎！”，我的意正在于此。“六艺”是论治之书，在《太史公自序 》之中有讲六家要旨，六家要旨司马谈统贯说“六家皆务为治”，太史公在《滑(gǔ，古)稽列传》里面也清楚地告诉你“六艺”《诗》《书》《礼》《乐》《易》《春秋》，“于治一也”都是为了论“治”，为了让天下治所著作的书，既然如此，这本《史记》要正面继承六艺，《史记》想当然也是论治之书，它不只是要记述过去的历史，更重要的是我们要(从)过去两千多年的历史中，提炼出共同的准则，能被后世的领导人所参考的大经大法，所以我们称赞《史记》为“百王大法”，其意义正在于此。“意在斯乎！意在斯乎！小子何敢让焉？”，中国人最重视“让”，中国人重礼，让者理之实也，什么叫作“让”？ 很简单，“让”就是原本应该是你的，而你不要，你要给别人，这才叫“让”。或者原本就不应该是你的，你让什么让，这跟你有什么关系。所以注意了什么才叫真“让”，就是那个东西理所当然就该是你的，而你居然不要，把这个东西给了别人，这叫做让，中国人最称赞“让”，把让看得无比重要，所以为什么尧舜被我们后来的人传颂，因为他们让国让天下，他们是实行禅让政治，所以中国人才推崇尧舜到那个地步去，因为“让”就有公心在背后，中国人强调这个。可是这么重视“让”的民族，你们更要注意他也有不让的时候，什么时候是“不让”的？ 孔子《论语》里面说“当仁不让于师”，大家注意他没有说当仁不让于父母，为什么？ 因为你所有的功劳都是你父母的，这是中国人传统观念，所以不能说当仁不让于父母，“当仁不让于师”，他有不让的时候。孔子说“当仁不让于师”，太史公在这里说“小子何敢让焉？”，什么才是中国人不让的东西？ 中国人什么都可以让，只有一样东西中国人是不让的，就是责任，责无旁贷，是你的责任你让什么让，你要让给谁，你都不愿意去扛那个责任，要谁来扛起，中国这个民族之伟大就在于，责任我们是不让的，当文化存亡绝续之际，就会有无数的中国读书人跑出来，自动自发地要承接这个责任，把中国的文化接续下去，所以我们才能成为五千年的文明古国，在无数的文明消亡之后，两河流域的文明、埃及的文明、希腊的文明而今安在哉？ 那么多的文明在世界历史都消亡了，为什么唯有中国文明能够长存？ 原因正在于此，我们有这么多了不起的读书人愿意把这个责任继承下来，在这一段《太史公自序》的文字中各位可以清楚明白地感受到这一点。

** 是余之罪也夫！

#+begin_quote
於是論次其文。七年而太史公遭李陵之禍，幽於縲紲。乃喟然而嘆曰：「是余之罪也夫！是余之罪也夫！身毀不用矣。」
#+end_quote

“于是论次其文” “七年” 在太初改历之后 太史公前后花了七年的时间 准备把《史记》的文字撰写起来 但是在这一年 太史公遇见他生命中的巨变 那是什么事情呢？ “而太史公遭李陵之祸，幽于缧(lěi)绁(xiè)。” “幽于缧绁” 就是被关起来了 为什么太史公会被关起来？ 在太史公的生命中有无比重要的意义 我必须详细跟各位说明 当然这件事情最好的说法 我们来看太史公自己是怎么谈的 而太史公把这件事情的前后经过 完完整整地写在他的《报任少卿书》中 这也是为了什么我们后面要上《报任少卿书》的原因 要了解太史公为什么作《史记》 了解《史记》一书的精华和要点何在 《太史公自序》和《报任少卿书》 是过去读书人不能不读的两篇文章 “李陵之祸”是怎么回事呢？ 简单地说 详细的说(法) 各位可以查相关的列传来看 而且我们后面《报任少卿书》也会再讲一次 所以我们现在简单地说 李广在汉代的将领中是非常有名的 可是李广一生的运气不够好 他一生都封不了侯 他没有封侯之命 李广在最后一次出征的时候 当时和总帅卫青约定了 什么时候要在哪里会师 可是李广迷路了 那么李广迷路了之后 他没有办法在那个时间到达那个地点 于是卫青就把李广给关起来 要送给武帝裁决 看武帝觉得李广应该处一个什么样的罪 因为李广在军中的威望非常大 结果李广在这个时候 他听见要送回去给武帝裁决 他心中觉得非常地悲愤而羞辱 于是就自杀了 那你就说 等一等 “失道”就是所谓的迷路 这个事情是李广自己的错 军中约什么时候在哪里见面 这个是军法 军法不能容情 李广有什么好悲愤的呢？ 这你就不明白了 如果你们把《史记》《汉书》相关的东西读一读 你就会发现 武帝用人是有偏好的 他对像卫青 像霍去病这样的人 常常是给他们最好的军队 给他们最好的补给 去走水草最多的路线 碰到的都是匈奴的主力 所以可以立大功 可是李广不同 李广往往在后勤补给上有所不足 走的通常都是水草最少 最难走的道路 常常碰不到匈奴的主力 因此李广容易迷路 跟这个事情是很有关系的 但是不管怎么样 李广悲愤自杀了 李广死了之后 李广的儿子李敢就想去报仇 他想跟大将军卫青报仇 他觉得是因为大将军卫青不公 所以他的父亲才会遭受到这样的结果 于是他就闯入大将军府里面 最后用剑刺伤了大将军 可是卫青这个人个性温和 他不想把这个事张扬出来 问题是卫青有一个亲戚叫做霍去病 那这个晚辈 听到这个事情非常生气 于是在有一次武帝出去狩猎的时候 霍去病 就因为卫青这件事情把李敢给杀了 李敢杀了之后 武帝为了掩盖霍去病的这个罪 于是就跟外面说 李敢是在打猎的时候被鹿撞死的 李家世代将门 可是世代都是这个下场 于是 李陵就觉得他要恢复父祖的事业 在那个时候 武帝准备北伐匈奴 他派去的主帅是李广利 而李陵这个时候告诉武帝 他愿意到北边去讨伐匈奴 汉武帝这个人最喜欢英雄人物 听到这个建议高兴得不得了 于是李陵就和他身边的壮士跑去讨伐匈奴了 可是问题来了 这一次的北伐匈奴 一开始李陵是节节胜利 他用步兵去迎战匈奴的骑兵 而匈奴竟然是打不过他的 可到最后 匈奴决定倾全国国力对付李陵 李陵就这样战败了 而李陵这一次的战败 传闻回来 武帝非常地难过 可是后来又有消息说 李陵投降了匈奴 于是武帝非常生气 把李陵的家族全部杀光光 这个时候朝廷的群臣们 在《报任少卿书》里面有说 刚开始武帝重视李陵的时候 人人都在称赞李陵是好将领 武帝是识人的君王 可是到李陵失败的时候 所有人都跳出来说李陵的坏话 “我们早就知道这个人看起来就不是个东西” 那这个时候在群臣说李陵坏话的时候 只有一个人跳出来帮李陵说话 那个人是谁呢？ 就是我们这一位太史公司马迁 他帮李陵说了好话之后 武帝非常的愤怒 于是把他下狱 注意啊 我先跟各位简单地说 后面《报任少卿书》还会详细讲 司马迁被汉武帝处的不是“宫刑” 很多书说“汉武帝处司马迁以宫刑” 这是错的 太史公 后面我们会解释这一点 太史公被武帝处的是“死刑” 在汉代 你被处死刑而你不想死 只有两个办法 一个办法是出钱 可以“赎死一等” 可是司马迁没有钱 另外一个办法就是“自请宫刑” 愿意进宫为宦官 可以“赎死一等” 你可以不用死 在这一刻 司马迁即将面对他生命中第二个重要的决定 他要选择死 还是要选择活下来把《史记》这部书完成 在这个时候 他“论次其文”七年 可是《史记》还没有完成 如果他在这一刻死了 这一本书就永远不会被后来的人所知道 我们今天就看不到这一本书 因为它没有完成 可是在那一刻 他做出他人生最艰难的决定 他接受了当时所有人都共同认为最耻辱的刑罚 就是宫刑 而要把这个命留下来 把《史记》完成 关于这一点 后面我们在《报任少卿书》的时候会详细地说它 而在这里《自序》对这个东西也有谈论 他说“幽于缧绁” 关到监狱里 “乃喟然而叹曰” 衷心地长叹说 “是余之罪也夫！是余之罪也夫！” 当年他父亲不能参加封禅大典 他说“是命也夫” 这里太史公不能够继续把《史记》完成下去 被关到监狱里 他说“是余之罪也夫” 这不是天 这是人 这是你自己 如果你有这样的宏图大志想要完成《史记》 你为什么要在这个时候出来帮李陵说话？ “身毁不用矣” 在这一刻他就告诉你 他的身已经毁了 不能用了 这是什么意思呢？ 注意了 中国人认为 受过肉刑的人 基本上不可能再从事任何事业了 因为政治容不下你 社会也容不下你 就一个读书人来说 如果这双方都容不下你 基本上你的功业也就到此为止了 但是 天无绝人之路 当你的现实的功业不能完成的时候 还有最后一条路你可以去做(走) 那条路是什么？

#+begin_quote
退而深惟曰：「夫詩書隱約者，欲遂其志之思也。

昔西伯拘羑里，演周易；孔子戹陳蔡，作春秋；屈原放逐，著離騷；左丘失明，厥有國語；孫子臏腳，而論兵法；不韋遷蜀，世傳呂覽；韓非囚秦，說難、孤憤；詩三百篇，大抵賢聖發憤之所為作也。此人皆意有所郁結，不得通其道也，故述往事，思來者。」

於是卒述陶唐以來，至于麟止，自黃帝始。
#+end_quote

我们看下面怎么说 “退而深惟曰” “深惟”就是深思 “夫《诗》《书》隐约者” 《诗》《书》为什么说是“隐约”呢？ 因为《诗》《书》之中往往是借由表面上的文字 去蕴含了其它的意思 所以叫做“隐约” “欲遂其志之思也” 作这些诗书的人 他心中有“志” 人最重要的就是“志” “志”是“士之心” 在中国人来看 人是为了志而活的 你这一生到底是为了什么而活的 那就是你的“志” 人最重要就是“立志” 到底你的志向何在 你这一生难道就只是为了白白虚度？ 就为了三顿饱 一个倒 老婆孩子热炕头吗？ 难道你这一生为的就只是为了吃饱等死吗？ 当然不是 中国人认为 你应该还有比这更崇高的东西 是你这一生首要完成的目标 你最想完成的那件事情就是你的“志” 所以孔子告诉你 “吾十有五而志于学” 我这一生的志 就在“学”这个字上 到最后他总结他一生 他说他自己“学而时习之” 我志在于学 而我最后确实学了 这叫做“遂其志” 可是问题来了 不是每一个人 每一种志 都有机会能够达成的 当你不能达成的时候该怎么办呢？ 有的人是因为时运不济 有的人是因为没有遇合(相遇而彼此投合) 有的人是因为环境或时代不允许 难道你就要就此放弃 灰心丧志吗？ 当然不是 中国人不这么说 中国人说 人生有三不朽 “立德” “立功” “立言” 这三不朽之路 我们今天把读书著作看成一个非常了不起的事 其实不是 在中国人看 读书著作当然了不起 可是在这三个之中 “立言”是排在最后一位的 为什么？ 因为中国人古代人认为 如果你有能力 你就应该在你活着的时候就把你的志向实现了 你这么厉害 为什么不在你活着的时候就把它做到呢？ 会去“立言”的人 往往都是因为在他活着的时候他没有办法完整地 实现他的志向 所以在他死了之前 他要把自己一生的“志” 把自己一生的“智慧” 自己一生的“心得” 写在书之中 希望千百年之后有人能来完成他的志向 千百年当新的时代来临之后 那个时代的人有适合的环境 可以把他的志向 终于做到它 这就是中国人为什么要“立言”的原因 因此会去“立言”的人 往往都是因为在当世不能够完成他的志 只能“欲遂其志之思也” 把他的“志之思”寄托在他的著作之中 我这样讲有没有根据呢？ 有 你看后面太史公所说的 “昔西伯拘羑(yǒu)里，演《周易》” 西伯被关在羑里这个地方的时候 就开始推演《易经》 “孔子厄陈蔡”之后 因为有“厄陈蔡”的巨变 所以才去作《春秋》 注意 并不是孔子在“厄陈蔡”的时候作《春秋》 这是概说 而是因为孔子 因为受到“厄陈蔡”的那个打击 最后他终于明白了 他改成了要以追求 要“立言”来流传后人 所以最后在回到鲁国之后 他就全力投入作《春秋》的事业 “屈原放逐，著《离骚》” 屈原也是因为在现实的仕途中不如意 被放逐之后才开始写《离骚》 “左丘失明，厥有《国语》” 这个人叫左丘明 可是左丘明的眼睛瞎了 一个瞎子 我跟你说 在古代来说 这样的人是没有办法 在政治上或社会上取得巨大成就的 在当时人来看 “左丘失明，厥有《国语》” 所以他才去写《国语》这部书 “孙子膑脚” 孙子被人把脚给砍了 所以才去论兵法 “不韦迁蜀，世传《吕览》” 注意 不韦传《吕览》 著作《吕氏春秋》其实是在他迁蜀之前 这里只是拿他来做个比方 我们取其意 不要疑其辞 不要一定要严格推求这个言辞 “韩非囚秦，《说难(shuì nàn)》《孤愤》” 韩非后来就给关在秦国里 流传后世的就是他《说难》跟《孤愤》 这些著名的著作 最后他得到了一个结论 “《诗》三百篇，大抵贤圣发愤之所为作也。” 《诗经》中的三百篇 绝大部分都是因为贤圣“发愤” 为什么要“发愤”？ 因为在他的时代不可能实现他的志向 所以 因为这样 才会去做这些东西 “之所为作也” “此人” 注意看 我们的根据就在这一句 “皆意有所郁结，不得通其道也” 他们为什么会去著作？ 都是因为在他们那个时代环境中 他们的“意有所郁结” 他们的“道”没有办法通达 所以“述往事” 拿过去的例子把它记述下来 “思来者” 为什么要“思来者”？ 因为写这部著作的目的是为了被来者观之 让以后的人可以看这部书 明白他是一个什么样的人 明白他的志向何在 告诉你为什么他想实现这样的志向 这样的志向要如何达成 于是 “述往事，思来者。” 《史记》也是如此 因为这样 《史记》就决定 “卒述陶唐以来” “陶唐”是唐尧 “至于麟止” “麟止”是指元狩元年武帝获麟的这件事情 在这里我们看到 《自序》之中写出了《史记》这个书的第一个上下限 它的上限是从尧开始 下限是到武帝元狩元年

** 欽念哉！欽念哉！

#+begin_quote
維我漢繼五帝末流，接三代（統）［絕］業。周道廢，秦撥去古文，焚滅詩書，故明堂石室金匱玉版圖籍散亂。

於是漢興，蕭何次律令，韓信申軍法，張蒼為章程，叔孫通定禮儀，則文學彬彬稍進，詩書往往閒出矣。
#+end_quote

#+begin_quote
自曹參薦蓋公言黃老，而賈生、晁錯明申、商，公孫弘以儒顯，百年之閒，天下遺文古事靡不畢集太史公。太史公仍父子相續纂其職。

曰：「於戲！余維先人嘗掌斯事，顯於唐虞，至于周，復典之，故司馬氏世主天官。至於余乎，欽念哉！欽念哉！」
#+end_quote

#+begin_quote
罔羅天下放失舊聞，王跡所興，原始察終，見盛觀衰，論考之行事，略推三代，錄秦漢，上記軒轅，下至于茲，著十二本紀，既科條之矣。

并時異世，年差不明，作十表。

禮樂損益，律歷改易，兵權山川鬼神，天人之際，承敝通變，作八書。
#+end_quote

** 成一家之言

#+begin_quote
二十八宿環北辰，三十輻共一轂，運行無窮，輔拂股肱之臣配焉，忠信行道，以奉主上，作三十世家。

扶義俶儻，不令己失時，立功名於天下，作七十列傳。
#+end_quote

“二十八宿环北辰，三十辐共一毂，运行无穷” 二十八宿都环绕 天上的星宿都是环绕着北极星而运转 地上的车轮 三十个车辐 也就是车轮中一个一个的辐条 都是环绕着中心的毂来运转 所以叫“三十辐共一毂，运行无穷” 因此 世家在记什么呢？ 在记“辅拂股肱之臣配焉” “忠信行道，以奉主上，作三十《世家》。” 他们专门记载那些围绕在天下中心的重要人物的事迹 这叫“三十世家” 可是天下 注意 天下有中心 也有围绕中心的重要人物 可是做历史的人不能只记这些人 这些人通常是指在政治上最有表现的人物 但是有很多人 他们非常了不起 只是因为时代的关系 他们在政治 在事功上没有那么了不起的表现 但我们不能不记这些人 所以《史记》还有专门一个体裁来记述这些人 “扶义俶傥，不令己失时” “立功名于天下，作七十《列传》。” 这些人未必是帝王 未必是诸侯 未必是宰执天下者 未必是围绕宰执天下者身边的重臣 可这些人在他们的人生中和事业中 都有伟大的表现 值得让后世人去认识这些人 这些人就叫“扶义俶傥，不令己失时，立功名与天下者” 我们要特别为这些人来写列传 这叫 “作七十<列传>”

#+begin_quote
凡百三十篇，五十二萬六千五百字，為太史公書。序略，以拾遺補闕，成一家之言，厥協六經異傳，整齊百家雜語，藏之名山，副在京師，俟後世聖人君子。第七十。

太史公曰：余述歷黃帝以來至太初而訖，百三十篇。
#+end_quote

前面已经把《史记》的五体都讲完了 本纪、表、书、世家、列传 这五体全部加起来刚好是一百三十篇 本纪十二篇 表十篇 书八篇 世家三十篇 列传七十篇 全部写出来告诉你 “凡百三十篇” 可是百三十篇还没有讲完 下面还接着一段很重要的文字 “五十二万六千五百字”啊 为什么太史公要详详细细地把它全书有多少字记载下来？ 各位从这个字数可以明白 第一点 太史公这部书确实完成了 是完成之后才有散佚 才有毁坏 绝不是他在一开始没有完成这部书 如果一开始没有完成 试问五十二万六千五百字是怎么数出来的？ 他能一个一个字数清楚 而且能够细到六千五百字这样的数字 就知道这部书是写完的了 第二点 他为什么要写清楚字数？ 因为在他之前有无数的书都已经被毁掉了 他希望后来的人能够知道这部书原来的样子是什么 我把字数写清楚了 就算这部书可能遭受毁掉的危机 后来的人也可以根据这个篇数 这个字数 重新去复原这本书 因此 他以防万一 他把这部书留下了两个本子 他从一开始著书的时候 就有正本跟副本 两部都是百三十篇 五十二万六千五百字 有没有用呢？ 坦白跟你讲 就防止毁坏这一点 半点用也没有 这部书要毁照毁 可对后世我们认识这部书很有用 因为有这两部书彼此 两个本子彼此互补 所以《史记》流传到今天 大致的原貌还不失 这正是太史公一开始的设计 为《太史公书》 特别要 特别注意这一点 《史记》的原名不叫做“史记” 在太史公著作的年代 “史记”是所有中国古代史书的通名 他这部书叫什么名字呢？ 这一部书的原名叫做《太史公》 “太史公”不只是尊称 它也是书名 你说既然是尊称 他对他父亲 对他自己的尊称 他怎么能同时也是书名呢？ 以作者为书名 这在中国古代是非常常见的事情 各位最熟悉的《孟子》《荀子》《韩非子》 难道不是以对作者的尊称来当做后世流传的书名吗？ 所以有这样的文化大传统是一点也不奇怪的 那你说 第二又会有同学问 可是老师这里明明写的是“太史公书” 不是“太史公”啊？ 你们如果去翻《史记》就知道 《史记》里面在书的后面 因为人名跟书名常常相同 为了标示两点 他在《孟子》后面会写 见《孟子》书 “余读《孟子》书” 他在书名的后面会再加上一个“书” 来标示我这里讲的是书 不是人 《汉书·艺文志》是当时对汉代秘府所藏书籍正式的记录 在《汉书·艺文志》中就明确地记载 这部书是“《太史公》，百三十篇。” 而不是“《太史公书》，百三十篇。” 它正式的书名是《太史公》 而不是《太史公书》 各位不妨把这个说法作为一个参考 “序略，以拾遗补蓺，成一家之言” 我写这个的目的是为了能够“拾遗补蓺” 能够对六艺进行一个旁通 对六艺进行一个辅助 这是他的自谦之词 可下面这一句话最重要 他要“成一家之言” 这就是为什么我们说《太史公》书中有子书的性质 原因就在于此 “成一家之言，厥协《六经》异传” 《六经》有不同的“传” “传”是用来解释“经”的 后来的弟子不同 解释经的说法也都不同 我希望能够把这些说法中进行调和 怎么调和呢？ 史家的方法就是考察它具体的事实 用事实来调和不同的说法 “整齐百家杂语” 我不但要调和六经 我还要整齐百家 你看 从“厥协”到“整齐” 就一步比一步程度要强烈 注意 下面这两句话很重要 “藏之名山，副在京师” 我告诉你们《史记》有两个本子嘛 根据就在这里跟《报任少卿书》中 他有两个本子 一个本子要藏之名山 一个本子副在京师 副本在京师 正本在名山 问题来了 名山是什么地方？ 在中国古代有两种不同的说法 一派的说法认为 名山是指名山大川 一派的说法认为 名山是指天子藏书的地方 这两种说法都有根据 也都说得通 你把书拿至名山大川 找一个风景优美的名山把书正本藏起来 这是说的通 所以有人认为 这里所谓的名山指的是太史公自己的家 而副在京师 这个京师指的就是京师中的秘府 因为京师的秘府确实有一部完整的《史记》藏本 那么再来了 另外一种认为藏之名山 名山指的是天子藏书的地方 副在京师是他把副本交给京师中的某人 让他保存副本 保存下去 这种说法也说得通 因为后来公布《太史(公)》这部书的 是太史公司马迁的外孙 叫做杨恽 他居住的地方就在京师 好 那么这两种说法到底谁对谁错呢？ 其实要解决这个问题很简单 在我的书《从史记到汉书》里面我也有考察这个问题 讲得非常清楚 《报任少卿书》里面 太史公同时又再提了一次他这两个本子 他当时说 他这个本子呢 “藏之名山，传之其人。” 正本藏在名山里面 副本“传之其人” 那我们从这两个来比对 正本“藏之名山” 两边都是一样 副本一个说“副在京师” 一个说“传之其人” 我们就知道这个“其人”指的就是京师中的某人 因为副本的这两边一搭就知道 “副在京师” “传之其人” 已经传给了京师的某人 而这个其人指的就应该不是国家的官府 而是一个私人 这个私人是太史公身边的人 后来杨恽公布的正是这个本子 而杨恽为什么能得到这个本子 因为太史公口中的“其人” 正是他的女儿和女婿 传给了他的女儿跟女婿 因此如果副本是“传之其人” 京师的某人 这样就可以知道 正本必然是指天子藏书的地方 而不是指哪个名山大川 所以“藏之名山” 我有一个本子藏在国家书府之中 “副在京师” 有一个本子已经传给了京师中的某人 一个是官方 一个是私人 两个本子在不同的环境下 不管环境怎么变动 前面因过六国的互相攻伐 史记散乱 所以藏在官府中的史书没有了 我为了以防万一 一个本子藏在私人 万一私人保不住 还有官府的那个本子 太史公在写完这部书以后 你想想 他花了多少心思来设计这样的一套东西 又用了什么样的想法 在忧惧他这部书会亡佚 所以你就知道 事隔两千多年 我们还能够读到这部书 这部书还能大体不失 这是多么幸运的事情 而这都要归功于太史公当初的设计 下面我们再来看这一段 太史公为什么要写《史记》这部书？ 前面我们讲到 为了接续父亲的事业 为了恢复祖先的光荣 为了能够承继周公和孔子的功业 前面不是讲到 周公次于孔子五百年 孔子到今天又五百年吗？ 为了接续周公孔子以来 天下的文化大道 可还有一个目的在这里 为的是等待后世的圣人君子 什么叫圣人君子？ 在中国古代人认为 圣人君子指的是有德有位的人 也就是未来有德的国家领导者们 我们希望著作这部书来等待后来的国家领导者们 这些国家领导者们是有德有位的 中国人这一点是最了不起的 就是中国人永远都有后望 他在他的当代完不成他的事业 他著作了这样了不起的书说我来寄托给后世的人 “第七十” 这一篇的次序


最后一句话 “太史公曰” “余述历黄帝以来至太初而讫，百三十篇。” 看到没有 这里《史记》的第三个上下限又跑出来 第一个上限是黄帝 就跟刚才的轩辕是重合的 再往后面一个下限是太初 到太初的时候 他记述的史实完毕了 一共是百三十篇

** 余述歷黃帝以來至太初而訖，百三十篇

那接下来当然各位同学读到这里就会有个疑问 老师 《史记》就在这一篇里面 注意还不是很多篇 就在这一篇《太史公自序》的最后这一部分 他前后提到了三个不同的上下限 第一个上(下)限是起于陶唐讫于麟止 对吧 第二个上(下)限是起于黄帝下至于兹 对吧 到现在 第三个是上至轩辕下到太初 对吧 那哪一个断限才是真的 各位同学有这样的疑问是很自然的事情 但是事实上我要告诉各位三个断限统统都是真的 你说老师 怎么可能三个断限都是真的 这三个断限是不一样的 这我就要告诉你 中国古代人写书跟今天写书不太相同 中国古代人写一个东西 书有写实 有写意 写实是为了写精确的年份 孔子到太史公司马谈的时候一共是三百七十多年 就会把年数数得清清楚楚 写意就可以说孔子自于今四百有余年 因为接下来就要到五百年圣人出那个时候了 这就是写实跟写意的差别 《史记》这本书在写的时候它就要继《春秋》 前面讲得很清楚 它要比附《春秋》 它要上继《春秋》 因为要继《春秋》 《春秋》这部书 我们就得注意《春秋》这部书 《春秋》这部书 孔子修《春秋》第一年始于鲁隐公元年 为什么要从鲁隐公开始修？ 难道鲁隐公之前鲁国没有君王吗？ 当然不是 鲁隐公之前鲁国已经有很多君王了 在西汉人的认知中 特别是公羊家的认知中 取这一年是有道理的 因为鲁隐公“让国” 我们要从“让”这个字开始写起 “让”是所有道德的根本 里面又以让国 让天下最为难得 所以我们要从鲁隐公开始写起 最后《春秋》总结 于鲁哀公十四年西狩获麟 得到了一头麒麟 因为《春秋》的开头是让国 最后是获麟 所以太史公一开始他的构想 也是从让国到获麟 从尧舜禅让一口气写到汉武帝获麟 开头跟结尾都能比附《春秋》 这在形式上 在写意上希望能跟《春秋》一致 来表达自己继《春秋》的意思 这是第一层意思 所以所谓从陶唐到麟止这个断限正是这么来的 可是问题来了 这是太史公写《史记》在我们现在来看 这恐怕是他的原始构想 《史记》这部书是希望从尧一直写到汉武帝获麟 但是太史公后来改变了这个计划 他决定不从尧开始写 而从黄帝开始写 为什么要从黄帝开始写？ 因为在太史公心中 中华文化这样辉煌伟大的文明有它的开头 这个开头应该从黄帝开始 所以要从文化的开始开始写 这就是为什么要起于黄帝的原因 可他就算从黄帝开始写 注意 在五帝本纪里面尧跟舜占了绝大的部分 仍然是五帝本纪中的重心 他仍然要褒扬他们的让德 所以把尧舜禅让的过程写得特别的清楚 他的下限呢？ 下限原本是希望写到麟止 后来他也改变了他的想法 虽然改变 但还是在太史公自序之中 保留了他原本说上自陶唐下至麟止 这就是一个写意的比附 让你知道这本书是继承《春秋》的 但在写实上他仍然以太初作为下限 但是各位要注意 同样是写实 他的上限和下限也有所谓的大限和小限 大限是指我大致上写到太初是我主体史事的完结 可是我不可能一刀切 所有的史事到太初 不管它结束没结束我都通通中断 如果要这样写法 它就不成为一个完整的历史了 所以我主要是到太初为止 但是这个事如果还有后续发展 我也会把这个后续发展完整地讲清楚 只要作者的生命还看得到 所以这里保留了一个下至于兹的提法 下至于兹就是一个 太初是一个准确的大限 而下至于兹是它的小限 因为不是所有的事都能够止于太初 好 那你就要问 老师 这个你讲的后面大限跟小限我们大概可以接受 可是写实跟写意你还有其他的根据吗？ 你怎么能说上至陶唐下至于兹 保留这个说法一定是为了比附《春秋》呢？ 因为还有一个具体的证据 就是刚刚各位所读到的“俟后世圣人君子” 因为《春秋》的最后 孔子也告诉你 我著《春秋》的目的 是为了俟后世君子 所以太史公在自序的最后 他也告诉你他要“俟后世圣人君子” 这不是和《春秋》的作意是相符的吗？ 这他想要继《春秋》 想要比附《春秋》的意思 在这几点上我们可以看得出是表露无疑的 而这一点我们就必须要谈到 太史公心中的《春秋》 在汉代指的是《春秋公羊传》 当时他们把这个当成是《春秋》的正统 而太史公的老师是董仲舒 董仲舒是《公羊春秋》的大师 他也承继了他老师董仲舒的这个想法 所以总结地来说 以写意 他是上起陶唐下讫麟止 以写实 他是上起轩辕或黄帝 他们是一致的 下到太初或于兹 其中的太初是大限 于兹是小限 在前面简单地介绍过《太史公自序》的本文之后 接下来我们要回头来看看 《太史公自序》究竟是一篇什么样的文字 《史记》是一个大部头的著作 大部头的著作的最后一篇 它也必然要是厚重的文字 这样才能收束得住 承载得起 《太史公自序》本身是一篇长篇 长篇文字到后面 它也必然要有个长段落的文字 才能够收束得住 乘载得起 文字本身“厚重”才不会让人觉得 整个行文有头重脚轻的疑虑 那么自序到最后它是怎么收束的呢？ 我们来看看 自序到最后它总共可以分成三层收束 第一层收束是前面一百二十九篇的序目 从黄帝 五帝本纪的序目 一路讲到货殖列传的序目 这是长篇文字 它是第一层收束 第二层收束是《太史公自序》本身的序目 它也是长篇文字作第二层收束 可是第三层收束它就不一定是长篇文字 但是气势本身必须要大 所以整个行文到最后一句 序目的最后一句 自序的最后一句 全书的最后一句 太史公就只用一句话镇住了整个行文 就是“太史公曰” “余述历黄帝以来至太初而讫，百三十篇。” 为什么这一句话本身足够厚重？ 因为这一句话本身也是分三层收束 “余述历黄帝以来”是谈全书的上限 “至太初而讫”谈全书的下限 这是第一层和第二层收束 “百三十篇”让你全书从头到尾有个通贯 这是第三层收束 所以自序本身到最后一个大段落有三层收束 而这个大段落到最后一句话 才又有三层收束 所以才叫收束得住 所以才叫乘载得起 你就会看出史公为文思考之周密 为什么要这么做？ 各位同学会有疑惑 写文章需要这么麻烦吗？ 需要 因为你要写一篇好文章 你要写一篇能够传世的文章 古人看文章是有门道的 古人看文章认为行文要像作画一样 你得从四点来看 第一点它的结构 它必须有结构、有布局、有气势 而且更重要是要有意境 结构严谨 太史公百三十篇 从自序的行文就可以看得出 它结构严谨 布局谨严 可是更难得是它的气势滔滔莽莽 源远流长 前人评之如长江黄河 为什么？ 它一开始就从他的祖先颛顼 远古的时代开始说起 一路蜿蜒而下 最后讲到他自己 再从头到尾把五帝以来到汉武(帝)的历史再通贯一遍 从一开头从上古时期开始的时候 接下来整个文章的流势大概可以分成五个大段落 第一个段落是讲他家的天官世家的源流 第二个段落是讲论六家要旨的意义 第三个段落是讲他父亲的临终托付 第四个段落是讲《史记》和《春秋》的关系 第五个段落就是把全书所有的序目再讲一遍 这五个大段落文气各异 所以前人说一个太史公自序 有如长江万里图一样 从深山遥远之处发源 一路流经各地 气势各异 可这样一幅滔滔莽莽的绘画 最重要就是最后 最后必须要有一句能够镇住全场的东西 自然造物极其奇妙 在长江的出海口有一个地方叫做佘山 佘山是一个非常非常小的岛 刚好就在长江出海口之处 因为有这个佘山 所以才能够镇住整个长江的气势 到这个地方才能够收讫 才能够平衡 所以以前的人说佘山还有另外一个美名 就叫做“万里石” 长江流经万里最后到这一块石头整个收束住 而《太史公自序》的最后一句话 “太史公曰” “余述历黄帝以来至太初而讫，百三十篇。” 正是整篇文章的长江万里石 正因为有这句话 《史记》到此作结 气势宏伟 没有头重脚轻之憾 好的 我们现在已经讲过自序这篇文章 有结构、有布局、有气势 可是更难能可贵的在于它有意境 不但有意境 而且意境深远 《史记》这篇自序的文章意境从哪里来呢? 它的意境就从它要接周孔 就从它要继《春秋》 就从它要俟后世君子 就从它要立百王大法而来

** 非僅一代良史，明為百王大法

接下来 我为各位谈论 《史记》这部书的特质到底是什么 《史记》这部书 一共有四个特质 在“史”部 它是正史鼻祖 这是所有人都公认的事实 我们看郑樵是怎么形容这部书的 他说 “使百代而下” “史官不能易其法，学者不能舍其书” “六经之后，惟有此作。” 你们看看“六经之后，惟有此作。” 就知道这部书在郑樵心中崇高的地位 而问题在于《史记》这部书从著成之后 后世所有的史书都沿袭它纪传体的体例 所有史书的内容都或多或少受到它重要的影响 那我们来看看这部“正史鼻祖” 为什么能够成为正史的开山始祖呢？ 原因是因为它首创纪传 它首先创立了纪传体 在《史记》之前 中国史书的正式体裁是编年体 按照年、时、月、日的次序 把事情一件一件地往下编 往下叙述 可是《史记》不是 它的纪传体基本上是以人物为中心 为本位 这在中国史学上是石破天惊的事情 因此他为了适应它的要求 他创立了所谓的“五体”的体裁 它包含“五体” “五体”是哪五“体”呢？ 本纪、表、书、世家、列传 “本纪”的目的在于“纪宰制天下者” 以“宰制天下者”为中心 我说“宰制天下者” 没有说他是帝王 项羽不是天子 吕后不是帝王 而这两个人都写在“本纪”之中 所以它是“宰制天下者”为中心 “表” 基本是把天下同时间发生的大事 把它编在一起 所以 前人多半把“表”当成资料表来读 个人认为这是一个大的损失 “表”者 “表天下之大势，与理乱兴亡之大略，而观一时之得失。” 这是我个人认为“表”的意义 以后有机会再详细跟各位说 “书” “八书”专门记制度 “世家” “三十世家” 专门记“宰制天下者”周围的“辅弼肱骨之臣”的事迹 而“列传”呢 则是除了“宰制天下者”和他身边的重臣之外 还有一些人应该在历史留名 史官要把他完完整整地记载下来 因此 《史记》的“五体”就有 本纪、表、书、世家、列传 总共五个体例 首创列(纪)传 包含五体 更难的是 这本书“体大思精” 在一个史书来说 这本书从它所能追溯到 中华文化最早的始祖 黄帝开始 一路写到它的当代为止 它是一部通史 只有通史 才能整体通贯地观察古今之变的发展 因此 郑樵非常赞许通史这样的体例 更难得的是 它不只在时间上是源远流长的通贯 它在空间上 太史公写的不只是当时的中国 他除了中国之外 他还写匈奴 他还写朝鲜 还写西南夷 还写西域 还写他所有已知道 当时已知的整个世界 太史公的《史记》它不只是一部中国史 它更是一部以中国为中心在当时来看的世界全史 因此 《史记》之所以能成为正史鼻祖 正在于它 首创纪传、包含五体、贯通古今、体大思精 这四点是后世其他的史书非常难以比得上的 第二点 在文学上 《史记》是所谓的“散文大宗” 我们后世把文学归类到“集”部去 《史记》为什么是散文大宗？ 因为它的行文不受年月限制 以人物为中心 中国的文体有“散文”和“韵文”两个大类 而学习散文没有能不看《史记》 所以你看到我的引文里面就说“学者为文” 没有人不读司马子长 就是司马迁 以及韩退之 韩愈的文字 韩愈是唐宋八大家之首 而在当时人来看 司马迁的文章还在他之前 还在他之上 这就是为什么 后来人推崇司马迁的文字为“雄、深、雅、健” “雄”是形容它的气势 “深”是形容它的涵义 光有气势有涵义 更难得的是它文字典雅 典雅的文字写得不好容易死气沉沉 可它文字“健” 让人看出来有勃勃生机 觉得自强不息 “雄、深、雅、健”这四个字如果再加以归纳 就是“雄、逸”二字 它一方面气势雄伟 一方面又有飘逸不可测之处 而这飘逸不可测之处 前人就常常说 《史记》的文章有“奇气” 什么叫做“奇气”？ 大凡古人为文 于起灭转接之间 如果有后人不可测识之处 那就是“奇气” 简单用白话文说 他写的东西 事前你想不到会这么出现这一个文字 读完了之后拍案叫绝 觉得写得真是太好 事后你要忘不了 这就叫作“奇气” 《史记》的文章 前人说有“雄、逸” 前人下面又评价韩文公 就是韩愈的文章“雄而不逸” 欧阳文忠公 欧阳修的文章“逸而不雄” 可这两家不过各得《史记》之一体 就足以成为当世散文大家 足以成为后世的文学大宗 你就看《史记》在文学上的地位究竟有多么崇高 而更难能可贵的是 《史记》一百三十篇 篇篇几乎都在塑造人物 都在描写时代 可是每一篇因为它所描写的人物不同 时代不同 每一篇的文风都完全不相同 篇篇都有它的独到之处 可以说 一篇是一个面貌 如果各位不相信 可以尝试看看 《秦始皇·本纪》的文字 就和《武帝·本纪》的风格是不相同的 《刺客列传》的文字 就和《孔子世家》又是另外一个面貌 这就是《史记》在文学上面了不起的地方 第三 在“子”部上 《史记》是“一家之言” 中国人把“家”这个字看得无比重要 不是什么人都能称“家” 称为“家”者 必然是因为他有他独特的思想 在清代 大家公认文章写得最好的是桐城 当时号称“天下文章出桐城” 桐城的人自称自己为“桐城家” 可是其他的人 后世的人只叫他们“桐城派” 你看一字之差 能差多远 为什么不能成“家”？ 因为成“家”要有自己独特的思想 司马谈“论六家要旨” 阴阳、儒、墨、名、法、道德 六家都有它了不起的思想 这就是他厉害的地方 而《史记》在这里它说自己成“一家之言” 它成哪一家之言？ 它成“史”家之言 它是正史鼻祖 更难得的是 它有自己史家独特的思想 所以它大胆地叫自己成“一家之言” 而后世的人都公认这一点 既然能成“一家之言” 它当然带有“子”部的性质 这是不用怀疑的事情 前面介绍了《史记》在“史”部 它是正史鼻祖 在“集”部 它是散文大宗 在“子”部 它是一家之言 这三个的成就都已经了不起了 但是这三个都不是《史记》最重要 也最特殊的价值所在 它最重要也最特殊的价值 在于它是“百王大法” 什么是“百王大法”？ 这必须从中国文化学术的大传统开始说起 中国在学术上的大传统 特别是在史学上 就是以“史”论“治” 中国最早论学 把战国诸子的学术分为六家 就是司马谈的《论六家要旨》 最后他总结于“六家皆务为治” 用一个“治”字贯穿六家 中国最早的典籍是六艺 诗、书、礼、乐、易、春秋 太史公在《史记》中 也明确地告诉你“六艺于治一也” 一样用个“治”字贯穿六艺 那么在六艺之中 和政治最有关系的有两部 一部是《尚书》 一部是《春秋》 太史公说“尚书长于政，春秋长于治人” “政”与“治人”相比 与“治”更有关系的 自然就是《春秋》 而《史记》在自序之中 说它这部书是为了“继春秋”而作 这一点我们就可以看出 《史记》本身更是一部“论治之书” 我们要明白“《史记》继春秋”这一点 就必须要重新问 在当时人 也就是西汉武帝时之前的人 他们到底是怎么看待《春秋》这部书的？ 我们今天认为《春秋》是一部史书 如果以史书的观点去看待《春秋》 那就会发现《春秋》不但是一部简单的史书 更是一部残缺的史书 我们就《春秋经》的本文来看 它的第一条就只有六个字 “元年春王正月” 一般我们写历史 一个完整的历史记载 必须要有时、要有地、要有人、要有事 可是《春秋经》开宗明义 第一条 它只有时 没有地、没有人、也没有事 所以用史学的观念来看 《春秋》不但是一本简单的史书 也是一本残缺的史书 所以前人才说这本书是“断烂朝报” 可在西汉人来看 《春秋》不只是一本史书 孔子是在借242年的历史的事情 来表达自己的微言大义 这是西汉人共同的认知 我们今天已经不能接受了 简单地说 孔子是拿这些事 作为假借 来表达伸张他心中 让三世人群 三世就是据乱世、升平世、太平世 进化的治道与治法 他如何让天下所有的人 能从据乱到升平到太平 一路到他最理想的境界 他把这些治道和治法 都寄托在他《春秋》这部书之内 因此汉代人认为 《春秋》不只是一本史书 它是“拨乱反正”之书 孔子“志在春秋” 孔子“志在春秋”是因为他认为 “拨乱世，反诸正，莫近乎《春秋》。” 所以《春秋》是“拨乱反正”之书 而《史记》“继春秋” 他当然也以“拨乱反正”作为他的志向 他用的方法是 将两千年的历史作整体贯通式的观察 要从里面找出 能被后世圣人君子所能遵循的 “大经与大法” 这个“大经与大法”是经得过历史考验的 从这个“大经与大法”才知道 治理天下到底应该怎么做 而这个“大经与大法”到底是什么呢？ 《史记》的内文非常多 不是三言两语所能讲得清楚的 在后面 我会尝试用一篇一篇具体的例子来为各位展现 《史记》中所说的“百王大法” 到底是怎么回事 它透过两千年中国历史的观察 它到底提炼出了什么样的治道与治法 但是在这一点上 说《史记》是“百王大法”的不是只有我 说《史记》是“百王大法”的 还有最早是清朝的包世臣 他就推崇《史记》这本书 “非仅一代良史” 真正的意义和价值正在于“百王大法”这四个字 因此我们要说 《史记》于“史”部 它是正史鼻祖 于“集”部 它是散文大宗 于“子”部 它是一家之言 于“经”部 它是百王大法 《史记》这部书之所以了不起 正在于它以一本书 而身兼经、史、子、集四部书的特质 “经、史、子、集”四部是后来的观念 在汉代人分“七略” 但是不管学术上怎么分类 像《史记》这样以一部书 贯通诸多不同领域的学术学问 而让它们总结于一体 这样的书在中国历史上 《史记》之后就没有第二本书了 《史记》之难能可贵 《史记》之崇高与特殊正在于这一点上

** 俟後世聖人君子

《史记》这本书为什么伟大？ 你们读完了自序全文之后就会发现 它伟大的原因在于以下几个 在于作者有工夫 我跟各位说过 中国做学问最重要的是工夫 如果你没有工夫 只靠着自己的聪明去应付事情 就容易因为聪明而走入歧途 他有工夫 也愿意下工夫 他的工夫不是一般人能下的 而是历父子二代接续着都在下工夫 第二个是因为作者有天才 做任何事情没有才能是不行的 你没有才能想要出类拔萃 那是万万不容易的 史公有没有天才 就看他写的文字就知道 在这篇文章里面 从自序的文章 你已经可以看出史公的才气 前人说太史公文字 疏宕有奇气 表面上看起来“疏” 其实厚重“宕” 而且厚重之外不是一板一眼死气沉沉 而是峰回路转 随时能带给你意想不到的感受 这叫做“有奇气” 疏宕有奇气 这没有身心体会 没有办法明白他的文字到底好在哪里 有工夫 有天才就够了吗？ 不够 还得有资料 历史学跟其他的学问不同 我们有隐居深山的隐士 我也相信有隐居深山的诗人 可是绝对没有隐居深山的史学家 为什么？ 因为做历史学必要史料 不能空口说白话 不能无中生有 很多时候你才气够 工夫够 可是你没有史料 没有史料就没有办法去写历史 可是太史公 刚好生在汉武帝没有战乱的时候 刚好天下遗文古事靡不毕集 太史公他统统看得到 因此他有资料 有工夫 有天才 有资料之外 他还有家世 他家是天官世家 是太史世家 天官世家和太史世家 赋给他过于常人的使命感和责任感 让他觉得责无旁贷 有家世之后 他还有教育背景 他的两个老师 孔安国和董仲舒 是当时西汉那个年代所能找到天下最好的老师 因此他父亲细心地教育栽培他 从年十岁则诵古文 找最好的老师 到二十岁而壮游天下 除了有教育以外 他还有历练 他曾经周游天下 看遍天下名山大川 也体会到了各式各样圣人所留下来的遗泽 因此他的见识胸襟远超过一般人 我们以上讲的这些东西 你们就应该接下来问我 难道老师有这些东西 就一定能代表 这部书能成为伟大的著作吗？ 我前面讲的这些东西 是做一部伟大著作的基本必要条件 没有以上的条件 你的著作不可能伟大 不可能出众 但是有这些条件 也不代表你的著作必然能够伟大出众 因为还有一个最关键的东西 那个东西是什么？ 那个东西就是境界 我们做人、读书 一般人靠的是自己的聪明 聪明已经不容易了 但是就如同我在第一讲一开头所说的 从聪明到智慧还有一段遥远的距离 那段距离是什么呢？ 那段距离就是 你必须要启发你的智慧 提炼你的智慧 把聪明变成智慧 把聪明变成智慧必须要读有智慧的书 接近有智慧的人 靠着历练不断地修正自己 可是光是有智慧就够了吗？ 不够 在中国人认为在聪明智慧之上 还有个更高的境界叫做天机 什么叫做天机呢？ 庄子说“嗜欲深者天机浅” 有些人不是不够聪明 不是没有处事的智慧 他最后为什么还得到如此糟糕的结局？ 因为他欲望太多 秦始皇如是 汉武帝也如是 你绝不能说这两个人没有智慧 他们处事的智慧绝对在你我之上百倍 可是问题是他们结局好吗？ 都不怎么好 为什么？ 因为他们嗜欲太深 欲令智昏 欲壑难填 人有了欲望就容易遮蔽你的眼睛 影响你的思考 想要免除这一点 庄子教你个办法 就是逐渐去掉自己的嗜欲 嗜欲深者天机浅 反过来说 嗜欲浅者就天机深 能够去掉多余的欲望 才能帮助你冷静客观地看待事物 也才能够与时迁移 应物变化 这是《论六家要旨》中的名句 可是光有天机 注意哦 天机还不同于我刚才所说的境界 境界是人跟人之间相比 最难赶上的东西 有时候有些人聪明未必如你 努力未必过你 可是他看事情的看法就是和你不一样 为什么 因为他境界比你高 那么我们就要问 境界从何而来？ 境界是靠聪明来的吗 不是 境界是靠努力来的吗 也不是 境界靠什么来呢 境界靠自我要求来 你想成为什么样的人 就决定了你将来会有什么样的境界 当然 所求乎上得乎其中 所求乎中得乎其下 你一心想成为圣人 最后未必真能成为圣人 但是你就算不能成为圣人 你的境界也绝对不会是个小人 这就是境界从自我追求来 一个立志成为圣贤英雄的人 能跟一个立志只想拿薪水混吃等死的人 他的境界会一样吗？ 一个立志想要做能够流传后世载之青史名著的人 能跟只想写文字混稿费 评职称的人是一样的吗？ 他当然是不一样的 他最后的成果也是不一样 当然 要成为什么境界的人 你必须下真工夫 要真求 不是嘴巴说说而已 太史公这部书为什么伟大？ 因为他有境界 他的境界从哪里来？ 就从忠孝心出而来 什么叫做孝？ 立身行道 扬名后世 以显父母 他要立志写出这样一部 继承他的父亲　写出这一部了不起的著作 让后世的人都知道 他和他父亲的名字 这就叫做孝 什么叫做忠？ 注意 忠不是忠君 忠者 尽己之谓忠 能够尽到自己的责任叫做忠 “君子素其位而行，不愿乎其外” 你在什么位置上 尽到那个责任 就叫做忠 你身为父亲 尽到父亲的责任叫忠 你身为人家的领导人 尽到领导人的责任叫忠 你是人家的属下 尽到人家属下的责任也叫忠 那太史公是什么 他是太史 太史有太史的责任 在中国史学存亡绝续之际 他觉得他自己责无旁贷 他要尽到自己的责任 正因如此 这部书从忠孝心出 因此它境界高 它能接周孔 继春秋 俟后世君子 立百王大法 这和后来一般书 一般人的境界是完全不相同的 因此他的成就也比一般人 一般著作要高得太多 从忠孝心出这个观念已经很难为现代人所理解的 因为古人思考事情从责任出发 君君臣臣 父父子子 讲的是君有君的责任 臣有臣的责任 父有父的责任 子有子的责任 不是讲君有君的权利 君有君的义务 你们明白了吗？ 今天的人用个人的观点 讲的是权利和义务 古人用全体的观点 这个全体不只包含了家 包含了国 包含了天下 也包含了祖先和子孙 因为从全体的观念出发 所以他们有责任 大丈夫 大人物 必有真性情 而想要尽到自己忠孝的责任 这就是太史公的真性情 因为有这样的真性情 有这样的自我要求 所以这部书才如此伟大 好的 那么最后讲到太史公自序讲到这里 你们更会想那全文应该已经讲好了 不 我们最后还要讲一件事情 一件非常重要的问题 我问你们各位一个问题 《史记》这部书是写给谁看的？ 前面我们讲过每一个文章 每一部书 往往作者都有个理想的读者 这个读者可能是一个人 可能是一群人 不一定 这一群人也有特定的条件 例如说我这个课 基本上就希望讲给大学生 或有大学生程度的社会人士听 那么基本上我们讲这样的课 有我们目标理想的读者 《史记》也不例外 我问问各位《史记》的理想读者是什么样的人？ 前面如果你们读过还没忘记 《史记》在最后说“俟后世圣人君子” 他的理想读者是圣人君子 这本书是写给圣人君子看的 明白这一点之后 我们就要自问 那我们是圣人君子吗？ 如果我们不是圣人君子 可是我们已经读了《史记》这本书 那该怎么办呢？ 难道这个问题不值得好好思考它一下吗？ 我跟各位说 我认为 如果我们不是圣人君子 而我们又读了《史记》这部书 而且深深为它的思想所感动 那我们就应该勉励自己成为圣人君子 圣人是什么？ 是人 君子是什么？ 君子是人 我们也是人 既然这本书是写给后世圣人君子看 人人皆可以为尧舜 人人皆可以为圣人君子 就看你有没有这样的自我要求 我们读了《史记》这部书 就应该勉励我们自己成为圣人君子 谢谢大家

** 总结

#+begin_quote
爱问：「至善只求诸心，恐于天下事理有不能尽。」先生曰：「心即理也。天下又有心外之事，心外之理乎？」

--传习录上
#+end_quote

# todo

* 写在后面
#+include: "../footer.zh.org"

* Footnotes

[fn:1] https://ctext.org/shiji/tai-shi-gong-zi-xu/zh
